using System.Text.RegularExpressions;
using System.Globalization;
namespace ZATCAMAUI.Core.Helper
{
    public static class CountryCodeHelper
    {
        // not used
        public static string IsoCountryCodeToFlagEmoji(this string country)
        {

            return string.Concat(country?.ToUpper().Select(x => char.ConvertFromUtf32(x + 0x1F1A5)));
        }
        // not used
        public static string GetFlag(string country)
        {
            var checkCountry = Regex.Replace(country, "[^a-zA-Z]+", "").ToLower();
            var regions = CultureInfo.GetCultures(CultureTypes.SpecificCultures).Select(x => new RegionInfo(x.LCID));
            var englishRegion = regions.FirstOrDefault(region => region.EnglishName.ToLower().Contains(checkCountry));
            if (englishRegion == null) return "🏳";
            var countryAbbrev = englishRegion.TwoLetterISORegionName;
            return countryAbbrev.IsoCountryCodeToFlagEmoji();
        }

        public static string[][] CountriesWithFlags = new string[][]
        {
            new string [] { "+93","Afghanistan","🇦🇫"},
             new string [] { "+355","Albania","🇦🇱"},
             new string [] { "+213","Algeria","🇩🇿"},
             new string [] { "+1 684","AmericanSamoa","🇦🇸"},
             new string [] { "+376","Andorra","🇦🇩"},
             new string [] { "+244","Angola","🇦🇴"},
             new string [] { "+1 264","Anguilla","🇦🇮"},
             new string [] { "+1268","Antigua and Barbuda","🇦🇬"},
             new string [] { "+54","Argentina","🇦🇷"},
             new string [] { "+374","Armenia","🇦🇲"},
             new string [] { "+297","Aruba","🇦🇼"},
             new string [] { "+61","Australia","🇦🇺"},
             new string [] { "+43","Austria","🇦🇹"},
             new string [] { "+994","Azerbaijan","🇦🇿"},
             new string [] { "+1 242","Bahamas","🇧🇸"},
             new string [] { "+973","Bahrain","🇧🇭"},
             new string [] { "+880","Bangladesh","🇧🇩"},
             new string [] { "+1 246","Barbados","🇧🇧"},
             new string [] { "+375","Belarus","🇧🇾"},
             new string [] { "+32","Belgium","🇧🇪"},
             new string [] { "+501","Belize","🇧🇿"},
             new string [] { "+229","Benin","🇧🇯"},
             new string [] { "+1 441","Bermuda","🇧🇲"},
             new string [] { "+975","Bhutan","🇧🇹"},
             new string [] { "+387","Bosnia and Herzegovina","🇧🇦"},
             new string [] { "+267","Botswana","🇧🇼"},
             new string [] { "+55","Brazil","🇧🇷"},
             new string [] { "+246","British Indian Ocean Territory","🇮🇴"},
             new string [] { "+359","Bulgaria","🇧🇬"},
             new string [] { "+226","Burkina Faso","🇧🇫"},
             new string [] { "+257","Burundi","🇧🇮"},
             new string [] { "+855","Cambodia","🇰🇭"},
             new string [] { "+237","Cameroon","🇨🇲"},
             new string [] { "+1","Canada","🇨🇦"},
             new string [] { "+238","Cape Verde","🇨🇻"},
             new string [] { "+ 345","Cayman Islands","🇰🇾"},
             new string [] { "+236","Central African Republic","🇨🇫"},
             new string [] { "+235","Chad","🇹🇩"},
             new string [] { "+56","Chile","🇨🇱"},
             new string [] { "+86","China","🇨🇳"},
             new string [] { "+61","Christmas Island","🇨🇽"},
             new string [] { "+57","Colombia","🇨🇴"},
             new string [] { "+269","Comoros","🇰🇲"},
             new string [] { "+242","Congo","🇨🇬"},
             new string [] { "+682","Cook Islands","🇨🇰"},
             new string [] { "+506","Costa Rica","🇨🇷"},
             new string [] { "+385","Croatia","🇭🇷"},
             new string [] { "+53","Cuba","🇨🇺"},
             new string [] { "+537","Cyprus","🇨🇾"},
             new string [] { "+420","Czech Republic","🇨🇿"},
             new string [] { "+45","Denmark","🇩🇰"},
             new string [] { "+253","Djibouti","🇩🇯"},
             new string [] { "+1 767","Dominica","🇩🇲"},
             new string [] { "+1 849","Dominican Republic","🇩🇴"},
             new string [] { "+593","Ecuador","🇪🇨"},
             new string [] { "+20","Egypt","🇪🇬"},
             new string [] { "+503","El Salvador","🇸🇻"},
             new string [] { "+240","Equatorial Guinea","🇬🇶"},
             new string [] { "+291","Eritrea","🇪🇷"},
             new string [] { "+372","Estonia","🇪🇪"},
             new string [] { "+251","Ethiopia","🇪🇹"},
             new string [] { "+298","Faroe Islands","🇫🇴"},
             new string [] { "+679","Fiji","🇫🇯"},
             new string [] { "+358","Finland","🇫🇮"},
             new string [] { "+33","France","🇫🇷"},
             new string [] { "+594","French Guiana","🇬🇫"},
             new string [] { "+689","French Polynesia","🇵🇫"},
             new string [] { "+241","Gabon","🇬🇦"},
             new string [] { "+220","Gambia","🇬🇲"},
             new string [] { "+995","Georgia","🇬🇪"},
             new string [] { "+49","Germany","🇩🇪"},
             new string [] { "+233","Ghana","🇬🇭"},
             new string [] { "+350","Gibraltar","🇬🇮"},
             new string [] { "+30","Greece","🇬🇷"},
             new string [] { "+299","Greenland","🇬🇱"},
             new string [] { "+1 473","Grenada","🇬🇩"},
             new string [] { "+590","Guadeloupe","🇬🇵"},
             new string [] { "+1 671","Guam","🇬🇺"},
             new string [] { "+502","Guatemala","🇬🇹"},
             new string [] { "+224","Guinea","🇬🇳"},
             new string [] { "+245","Guinea-Bissau","🇬🇼"},
             new string [] { "+595","Guyana","🇬🇾"},
             new string [] { "+509","Haiti","🇭🇹"},
             new string [] { "+504","Honduras","🇭🇳"},
             new string [] { "+36","Hungary","🇭🇺"},
             new string [] { "+354","Iceland","🇮🇸"},
             new string [] { "+91","India","🇮🇳"},
             new string [] { "+62","Indonesia","🇮🇩"},
             new string [] { "+964","Iraq","🇮🇶"},
             new string [] { "+353","Ireland","🇮🇪"},
             //new string [] { "+972","Israel","🇮🇱"}
             new string [] { "+39","Italy","🇮🇹"},
             new string [] { "+1 876","Jamaica","🇯🇲"},
             new string [] { "+81","Japan","🇯🇵"},
             new string [] { "+962","Jordan","🇯🇴"},
             new string [] { "+7 7","Kazakhstan","🇰🇿"},
             new string [] { "+254","Kenya","🇰🇪"},
             new string [] { "+686","Kiribati","🇰🇮"},
             new string [] { "+965","Kuwait","🇰🇼"},
             new string [] { "+996","Kyrgyzstan","🇰🇬"},
             new string [] { "+371","Latvia","🇱🇻"},
             new string [] { "+961","Lebanon","🇱🇧"},
             new string [] { "+266","Lesotho","🇱🇸"},
             new string [] { "+231","Liberia","🇱🇷"},
             new string [] { "+423","Liechtenstein","🇱🇮"},
             new string [] { "+370","Lithuania","🇱🇹"},
             new string [] { "+352","Luxembourg","🇱🇺"},
             new string [] { "+261","Madagascar","🇲🇬"},
             new string [] { "+265","Malawi","🇲🇼"},
             new string [] { "+60","Malaysia","🇲🇾"},
             new string [] { "+960","Maldives","🇲🇻"},
             new string [] { "+223","Mali","🇲🇱"},
             new string [] { "+356","Malta","🇲🇹"},
             new string [] { "+692","Marshall Islands","🇲🇭"},
             new string [] { "+596","Martinique","🇲🇶"},
             new string [] { "+222","Mauritania","🇲🇷"},
             new string [] { "+230","Mauritius","🇲🇺"},
             new string [] { "+262","Mayotte","🇾🇹"},
             new string [] { "+52","Mexico","🇲🇽"},
             new string [] { "+377","Monaco","🇲🇨"},
             new string [] { "+976","Mongolia","🇲🇳"},
             new string [] { "+382","Montenegro","🇲🇪"},
             new string [] { "+1664","Montserrat","🇲🇸"},
             new string [] { "+212","Morocco","🇲🇦"},
             new string [] { "+95","Myanmar","🇲🇲"},
             new string [] { "+264","Namibia","🇳🇦"},
             new string [] { "+674","Nauru","🇳🇷"},
             new string [] { "+977","Nepal","🇳🇵"},
             new string [] { "+31","Netherlands","🇳🇱"},
             new string [] { "+599","Netherlands Antilles","🇳🇱"},
             new string [] { "+687","New Caledonia","🇳🇨"},
             new string [] { "+64","New Zealand","🇳🇿"},
             new string [] { "+505","Nicaragua","🇳🇮"},
             new string [] { "+227","Niger","🇳🇪"},
             new string [] { "+234","Nigeria","🇳🇬"},
             new string [] { "+683","Niue","🇳🇺"},
             new string [] { "+1670","Northern Mariana Islands","🇲🇵"},
             new string [] { "+47","Norway","🇳🇴"},
             new string [] { "+968","Oman","🇴🇲"},
             new string [] { "+92","Pakistan","🇵🇰"},
             new string [] { "+680","Palau","🇵🇼"},
             new string [] { "+507","Panama","🇵🇦"},
             new string [] { "+675","Papua New Guinea","🇵🇬"},
             new string [] { "+595","Paraguay","🇵🇾"},
             new string [] { "+51","Peru","🇵🇪"},
             new string [] { "+63","Philippines","🇵🇭"},
             new string [] { "+48","Poland","🇵🇱"},
             new string [] { "+351","Portugal","🇵🇹"},
             new string [] { "+1939","Puerto Rico","🇵🇷"},
             new string [] { "+974","Qatar","🇶🇦"},
             new string [] { "+40","Romania","🇷🇴"},
             new string [] { "+250","Rwanda","🇷🇼"},
             new string [] { "+685","Samoa","🇼🇸"},
             new string [] { "+378","San Marino","🇸🇲"},
             new string [] { "+966","Saudi Arabia","🇸🇦"},
             new string [] { "+221","Senegal","🇸🇳"},
             new string [] { "+381","Serbia","🇷🇸"},
             new string [] { "+248","Seychelles","🇸🇨"},
             new string [] { "+232","Sierra Leone","🇸🇱"},
             new string [] { "+65","Singapore","🇸🇬"},
             new string [] { "+421","Slovakia","🇸🇰"},
             new string [] { "+386","Slovenia","🇸🇮"},
             new string [] { "+677","Solomon Islands","🇸🇧"},
             new string [] { "+27","South Africa","🇿🇦"},
             new string [] { "+500","South Georgia and the South Sandwich Islands","🇬🇸"},
             new string [] { "+34","Spain","🇪🇸"},
             new string [] { "+94","Sri Lanka","🇱🇰"},
             new string [] { "+249","Sudan","🇸🇩"},
             new string [] { "+597","Suriname","🇸🇷"},
             new string [] { "+268","Swaziland","🇸🇿"},
             new string [] { "+46","Sweden","🇸🇪"},
             new string [] { "+41","Switzerland","🇨🇭"},
             new string [] { "+992","Tajikistan","🇹🇯"},
             new string [] { "+66","Thailand","🇹🇭"},
             new string [] { "+228","Togo","🇹🇬"},
             new string [] { "+690","Tokelau","🇹🇰"},
             new string [] { "+676","Tonga","🇹🇴"},
             new string [] { "+1 868","Trinidad and Tobago","🇹🇹"},
             new string [] { "+216","Tunisia","🇹🇳"},
             new string [] { "+90","Turkey","🇹🇷"},
             new string [] { "+993","Turkmenistan","🇹🇲"},
             new string [] { "+1 649","Turks and Caicos Islands","🇹🇨"},
             new string [] { "+688","Tuvalu","🇹🇻"},
             new string [] { "+256","Uganda","🇺🇬"},
             new string [] { "+380","Ukraine","🇺🇦"},
             new string [] { "+971","United Arab Emirates","🇦🇪"},
             new string [] { "+44","United Kingdom","🇬🇧"},
             new string [] { "+1","United States","🇺🇸"},
             new string [] { "+598","Uruguay","🇺🇾"},
             new string [] { "+998","Uzbekistan","🇺🇿"},
             new string [] { "+678","Vanuatu","🇻🇺"},
             new string [] { "+681","Wallis and Futuna","🇼🇫"},
             new string [] { "+967","Yemen","🇾🇪"},
             new string [] { "+260","Zambia","🇿🇲"},
             new string [] { "+263","Zimbabwe","🇿🇼"},
             new string [] { "+358","Åland Islands","🇦🇽"},
             new string [] { "+672","Antarctica","🇦🇶"},
             new string [] { "+591","Bolivia, Plurinational State of","🇧🇴"},
             new string [] { "+673","Brunei Darussalam","🇧🇳"},
             new string [] { "+61","Cocos (Keeling) Islands","🇨🇨"},
             new string [] { "+243","Congo, The Democratic Republic of the","🇨🇩"},
             new string [] { "+225","Cote d'Ivoire","🇨🇮"},
             new string [] { "+500","Falkland Islands (Malvinas)","🇫🇰"},
             new string [] { "+44","Guernsey","🇬🇬"},
             new string [] { "+379","Holy See (Vatican City State)","🇻🇦"},
             new string [] { "+852","Hong Kong","🇭🇰"},
             new string [] { "+98","Iran, Islamic Republic of","🇮🇷"},
             new string [] { "+44","Isle of Man","🇮🇲"},
             new string [] { "+44","Jersey","🇯🇪"},
             new string [] { "+850","Korea, Democratic People's Republic of","🇰🇵"},
             new string [] { "+82","Korea, Republic of","🇰🇷"},
             new string [] { "+856","Lao People's Democratic Republic","🇱🇦"},
             new string [] { "+218","Libyan Arab Jamahiriya","🇱🇾"},
             new string [] { "+853","Macao","🇲🇴"},
             new string [] { "+389","Macedonia, The Former Yugoslav Republic of","🇲🇰"},
             new string [] { "+691","Micronesia, Federated States of","🇫🇲"},
             new string [] { "+373","Moldova, Republic of","🇲🇩"},
             new string [] { "+258","Mozambique","🇲🇿"},
             new string [] { "+970","Palestinian Territory, Occupied","🇵🇸"},
             new string [] { "+872","Pitcairn","🇵🇳"},
             new string [] { "+262","Réunion","🇷🇪"},
             new string [] { "+7","Russia","🇷🇺"},
             new string [] { "+590","Saint Barthélemy","🇧🇱"},
             new string [] { "+290","Saint Helena, Ascension and Tristan Da Cunha","🇸🇭"},
             new string [] { "+1 869","Saint Kitts and Nevis","🇰🇳"},
             new string [] { "+1 758","Saint Lucia","🇱🇨"},
             new string [] { "+590","Saint Martin","🇲🇫"},
             new string [] { "+508","Saint Pierre and Miquelon","🇵🇲"},
             new string [] { "+1 784","Saint Vincent and the Grenadines","🇻🇨"},
             new string [] { "+239","Sao Tome and Principe","🇸🇹"},
             new string [] { "+252","Somalia","🇸🇴"},
             new string [] { "+47","Svalbard and Jan Mayen","🇸🇯"},
             new string [] { "+963","Syrian Arab Republic","🇸🇾"},
             new string [] { "+886","Taiwan, Province of China","🇹🇼"},
             new string [] { "+255","Tanzania, United Republic of","🇹🇿"},
             new string [] { "+670","Timor-Leste","🇹🇱"},
             new string [] { "+58","Venezuela, Bolivarian Republic of","🇻🇪"},
             new string [] { "+84","Viet Nam","🇻🇳"},
             new string [] { "+1 284","Virgin Islands, British","🇻🇬"},
             new string [] { "+1 340","Virgin Islands, U.S.","🇻🇮"},

        };
        public static string[][] Countries = new string[][]
            {
                new string  []  { "Afghanistan",     "+93",     "AF"  },
                  new string  []  { "Albania",     "+355",     "AL"  },
                  new string  []  { "Algeria",     "+213",     "DZ"  },
                  new string  []  { "AmericanSamoa",     "+1 684",    "AS"  },
                  new string  []  { "Andorra",     "+376",     "AD"  },
                  new string  []  { "Angola",     "+244",     "AO"  },
                  new string  []  { "Anguilla",     "+1 264",     "AI"  },
                  new string  []  { "Antigua and Barbuda",     "+1268",     "AG"  },
                  new string  []  { "Argentina",     "+54",     "AR"  },
                  new string  []  { "Armenia",     "+374",     "AM"  },
                  new string  []  { "Aruba",     "+297",     "AW"  },
                  new string  []  { "Australia",     "+61",     "AU"  },
                  new string  []  { "Austria",     "+43",     "AT"  },
                  new string  []  { "Azerbaijan",     "+994",    "AZ"  },
                  new string  []  { "Bahamas",     "+1 242",     "BS"  },
                  new string  []  { "Bahrain",     "+973",     "BH"  },
                  new string  []  { "Bangladesh",     "+880",     "BD"  },
                  new string  []  { "Barbados",     "+1 246",     "BB"  },
                  new string  []  { "Belarus",     "+375",     "BY"  },
                  new string  []  { "Belgium",     "+32",     "BE"  },
                  new string  []  { "Belize",     "+501",     "BZ"  },
                  new string  []  { "Benin",     "+229",     "BJ"  },
                  new string  []  { "Bermuda",     "+1 441",     "BM"  },
                  new string  []  { "Bhutan",     "+975",     "BT"  },
                  new string  []  { "Bosnia and Herzegovina",     "+387",     "BA"  },
                  new string  []  { "Botswana",     "+267",     "BW"  },
                  new string  []  { "Brazil",     "+55",     "BR"  },
                  new string  []  { "British Indian Ocean Territory",     "+246",     "IO"  },
                  new string  []  { "Bulgaria",     "+359",     "BG"  },
                  new string  []  { "Burkina Faso",     "+226",     "BF"  },
                  new string  []  { "Burundi",     "+257",     "BI"  },
                  new string  []  { "Cambodia",     "+855",     "KH"  },
                  new string  []  { "Cameroon",     "+237",     "CM"  },
                  new string  []  { "Canada",     "+1",     "CA"  },
                  new string  []  { "Cape Verde",     "+238",     "CV"  },
                  new string  []  { "Cayman Islands",     "+ 345",     "KY"  },
                  new string  []  { "Central African Republic",     "+236",     "CF"  },
                  new string  []  { "Chad",     "+235",     "TD"  },
                  new string  []  { "Chile",     "+56",     "CL"  },
                  new string  []  { "China",     "+86",     "CN"  },
                  new string  []  { "Christmas Island",     "+61",     "CX"  },
                  new string  []  { "Colombia",     "+57",     "CO"  },
                  new string  []  { "Comoros",     "+269",     "KM"  },
                  new string  []  { "Congo",     "+242",     "CG"  },
                  new string  []  { "Cook Islands",     "+682",     "CK"  },
                  new string  []  { "Costa Rica",     "+506",     "CR"  },
                  new string  []  { "Croatia",     "+385",     "HR"  },
                  new string  []  { "Cuba",     "+53",     "CU"  },
                  new string  []  { "Cyprus",     "+537",     "CY"  },
                  new string  []  { "Czech Republic",     "+420",     "CZ"  },
                  new string  []  { "Denmark",     "+45",     "DK"  },
                  new string  []  { "Djibouti",     "+253",     "DJ"  },
                  new string  []  { "Dominica",     "+1 767",     "DM"  },
                  new string  []  { "Dominican Republic",     "+1 849",     "DO"  },
                  new string  []  { "Ecuador",     "+593",     "EC"  },
                  new string  []  { "Egypt",     "+20",     "EG"  },
                  new string  []  { "El Salvador",     "+503",     "SV"  },
                  new string  []  { "Equatorial Guinea",     "+240",     "GQ"  },
                  new string  []  { "Eritrea",     "+291",     "ER"  },
                  new string  []  { "Estonia",     "+372",     "EE"  },
                  new string  []  { "Ethiopia",     "+251",     "ET"  },
                  new string  []  { "Faroe Islands",     "+298",     "FO"  },
                  new string  []  { "Fiji",     "+679",     "FJ"  },
                  new string  []  { "Finland",     "+358",     "FI"  },
                  new string  []  { "France",     "+33",     "FR"  },
                  new string  []  { "French Guiana",     "+594",     "GF"  },
                  new string  []  { "French Polynesia",     "+689",     "PF"  },
                  new string  []  { "Gabon",     "+241",     "GA"  },
                  new string  []  { "Gambia",     "+220",     "GM"  },
                  new string  []  { "Georgia",    "+995",     "GE"  },
                  new string  []  { "Germany",     "+49",     "DE"  },
                  new string  []  { "Ghana",     "+233",     "GH"  },
                  new string  []  { "Gibraltar",     "+350",    "GI"  },
                  new string  []  { "Greece",     "+30",     "GR"  },
                  new string  []  { "Greenland",     "+299",     "GL"  },
                  new string  []  { "Grenada",     "+1 473",     "GD"  },
                  new string  []  { "Guadeloupe",     "+590",     "GP"  },
                  new string  []  { "Guam",     "+1 671",     "GU"  },
                  new string  []  { "Guatemala",     "+502",     "GT"  },
                  new string  []  { "Guinea",     "+224",     "GN"  },
                  new string  []  { "Guinea-Bissau",     "+245",     "GW"  },
                  new string  []  { "Guyana",     "+595",     "GY"  },
                  new string  []  { "Haiti",     "+509",     "HT"  },
                  new string  []  { "Honduras",     "+504",     "HN"  },
                  new string  []  { "Hungary",     "+36",     "HU"  },
                  new string  []  { "Iceland",     "+354",     "IS"  },
                  new string  []  { "India",     "+91",     "IN"  },
                  new string  []  { "Indonesia",     "+62",     "ID"  },
                  new string  []  { "Iraq",     "+964",     "IQ"  },
                  new string  []  { "Ireland",     "+353",     "IE"  },
                  new string  []  { "Israel",     "+972",     "IL"  },
                  new string  []  { "Italy",     "+39",     "IT"  },
                  new string  []  { "Jamaica",     "+1 876",     "JM"  },
                  new string  []  { "Japan",     "+81",     "JP"  },
                  new string  []  { "Jordan",     "+962",     "JO"  },
                  new string  []  { "Kazakhstan",     "+7 7",     "KZ"  },
                  new string  []  { "Kenya",     "+254",     "KE"  },
                  new string  []  { "Kiribati",     "+686",     "KI"  },
                  new string  []  { "Kuwait",     "+965",     "KW"  },
                  new string  []  { "Kyrgyzstan",     "+996",     "KG"  },
                  new string  []  { "Latvia",     "+371",     "LV"  },
                  new string  []  { "Lebanon",     "+961",     "LB"  },
                  new string  []  { "Lesotho",     "+266",     "LS"  },
                  new string  []  { "Liberia",     "+231",     "LR"  },
                  new string  []  { "Liechtenstein",     "+423",     "LI"  },
                  new string  []  { "Lithuania",     "+370",     "LT"  },
                  new string  []  { "Luxembourg",     "+352",     "LU"  },
                  new string  []  { "Madagascar",     "+261",     "MG"  },
                  new string  []  { "Malawi",     "+265",     "MW"  },
                  new string  []  { "Malaysia",     "+60",     "MY"  },
                  new string  []  { "Maldives",     "+960",     "MV"  },
                  new string  []  { "Mali",     "+223",    "ML"  },
                  new string  []  { "Malta",     "+356",     "MT"  },
                  new string  []  { "Marshall Islands",     "+692",     "MH"  },
                  new string  []  { "Martinique",     "+596",     "MQ"  },
                  new string  []  { "Mauritania",     "+222",     "MR"  },
                  new string  []  { "Mauritius",     "+230",     "MU"  },
                  new string  []  { "Mayotte",     "+262",     "YT"  },
                  new string  []  { "Mexico",     "+52",     "MX"  },
                  new string  []  { "Monaco",     "+377",     "MC"  },
                  new string  []  { "Mongolia",     "+976",     "MN"  },
                  new string  []  { "Montenegro",     "+382",     "ME"  },
                  new string  []  { "Montserrat",     "+1664",     "MS"  },
                  new string  []  { "Morocco",    "+212",     "MA"  },
                  new string  []  { "Myanmar",     "+95",     "MM"  },
                  new string  []  { "Namibia",     "+264",     "NA"  },
                  new string  []  { "Nauru",     "+674",     "NR"  },
                  new string  []  { "Nepal",     "+977",     "NP"  },
                  new string  []  { "Netherlands",     "+31",     "NL"  },
                  new string  []  { "Netherlands Antilles",     "+599",     "AN"  },
                  new string  []  { "New Caledonia",     "+687",     "NC"  },
                  new string  []  { "New Zealand",     "+64",     "NZ"  },
                  new string  []  { "Nicaragua",     "+505",     "NI"  },
                  new string  []  { "Niger",     "+227",     "NE"  },
                  new string  []  { "Nigeria",     "+234",     "NG"  },
                  new string  []  { "Niue",     "+683",     "NU"  },
                  new string  []  { "Northern Mariana Islands",     "+1670",     "MP"  },
                  new string  []  { "Norway",     "+47",     "NO"  },
                  new string  []  { "Oman",     "+968",     "OM"  },
                  new string  []  { "Pakistan",     "+92",     "PK"  },
                  new string  []  { "Palau",     "+680",     "PW"  },
                  new string  []  { "Panama",     "+507",     "PA"  },
                  new string  []  { "Papua New Guinea",     "+675",     "PG"  },
                  new string  []  { "Paraguay",     "+595",     "PY"  },
                  new string  []  { "Peru",     "+51",     "PE"  },
                  new string  []  { "Philippines",     "+63",     "PH"  },
                  new string  []  { "Poland",     "+48",     "PL"  },
                  new string  []  { "Portugal",     "+351",     "PT"  },
                  new string  []  { "Puerto Rico",    "+1939",     "PR"  },
                  new string  []  { "Qatar",     "+974",     "QA"  },
                  new string  []  { "Romania",     "+40",     "RO"  },
                  new string  []  { "Rwanda",     "+250",     "RW"  },
                  new string  []  { "Samoa",     "+685",     "WS"  },
                  new string  []  { "San Marino",     "+378",     "SM"  },
                  new string  []  { "Saudi Arabia",     "+966",     "SA"  },
                  new string  []  { "Senegal",     "+221",     "SN"  },
                  new string  []  { "Serbia",     "+381",     "RS"  },
                  new string  []  { "Seychelles",     "+248",     "SC"  },
                  new string  []  { "Sierra Leone",     "+232",     "SL"  },
                  new string  []  { "Singapore",     "+65",    "SG"  },
                  new string  []  { "Slovakia",     "+421",     "SK"  },
                  new string  []  { "Slovenia",     "+386",     "SI"  },
                  new string  []  { "Solomon Islands",     "+677",     "SB"  },
                  new string  []  { "South Africa",     "+27",     "ZA"  },
                  new string  []  { "South Georgia and the South Sandwich Islands",     "+500",     "GS"  },
                  new string  []  { "Spain",     "+34",     "ES"  },
                  new string  []  { "Sri Lanka",     "+94",     "LK"  },
                  new string  []  { "Sudan",     "+249",     "SD"  },
                  new string  []  { "Suriname",     "+597",     "SR"  },
                  new string  []  { "Swaziland",     "+268",     "SZ"  },
                  new string  []  { "Sweden",     "+46",     "SE"  },
                  new string  []  { "Switzerland",     "+41",     "CH"  },
                  new string  []  { "Tajikistan",     "+992",     "TJ"  },
                  new string  []  { "Thailand",     "+66",     "TH"  },
                  new string  []  { "Togo",     "+228",     "TG"  },
                  new string  []  { "Tokelau",     "+690",     "TK"  },
                  new string  []  { "Tonga",     "+676",     "TO"  },
                  new string  []  { "Trinidad and Tobago",     "+1 868",     "TT"  },
                  new string  []  { "Tunisia",     "+216",     "TN"  },
                  new string  []  { "Turkey",     "+90",     "TR"  },
                  new string  []  { "Turkmenistan",     "+993",     "TM"  },
                  new string  []  { "Turks and Caicos Islands",     "+1 649",     "TC"  },
                  new string  []  { "Tuvalu",     "+688",    "TV"  },
                  new string  []  { "Uganda",     "+256",     "UG"  },
                  new string  []  { "Ukraine",     "+380",     "UA"  },
                  new string  []  { "United Arab Emirates",     "+971",     "AE"  },
                  new string  []  { "United Kingdom",     "+44",     "GB"  },
                  new string  []  { "United States",     "+1",     "US"  },
                  new string  []  { "Uruguay",     "+598",     "UY"  },
                  new string  []  { "Uzbekistan",     "+998",     "UZ"  },
                  new string  []  { "Vanuatu",     "+678",     "VU"  },
                  new string  []  { "Wallis and Futuna",     "+681",     "WF"  },
                  new string  []  { "Yemen",     "+967",     "YE"  },
                  new string  []  { "Zambia",    "+260",     "ZM"  },
                  new string  []  { "Zimbabwe",     "+263",     "ZW"  },
                  new string  []  { "Åland Islands",     "+358",     "AX"  },
                  new string  []  { "Antarctica",     "+672",     "AQ"  },
                  new string  []  { "Bolivia, Plurinational State of",     "+591",     "BO"  },
                  new string  []  { "Brunei Darussalam",     "+673",     "BN"  },
                  new string  []  { "Cocos (Keeling) Islands",     "+61",     "CC"  },
                  new string  []  { "Congo, The Democratic Republic of the",     "+243",     "CD"  },
                  new string  []  { "Cote d'Ivoire",     "+225",     "CI"  },
                  new string  []  { "Falkland Islands (Malvinas)",     "+500",     "FK"  },
                  new string  []  { "Guernsey",     "+44",     "GG"  },
                  new string  []  { "Holy See (Vatican City State)",     "+379",     "VA"  },
                  new string  []  { "Hong Kong",     "+852",     "HK"  },
                  new string  []  { "Iran, Islamic Republic of",     "+98",     "IR"  },
                  new string  []  { "Isle of Man",     "+44",     "IM"  },
                  new string  []  { "Jersey",     "+44",     "JE"  },
                  new string  []  { "Korea, Democratic People's Republic of",     "+850",     "KP"  },
                  new string  []  { "Korea, Republic of",     "+82",     "KR"  },
                  new string  []  { "Lao People's Democratic Republic",     "+856",     "LA"  },
                  new string  []  { "Libyan Arab Jamahiriya",     "+218",     "LY"  },
                  new string  []  { "Macao",     "+853",     "MO"  },
                  new string  []  { "Macedonia, The Former Yugoslav Republic of",     "+389",     "MK"  },
                  new string  []  { "Micronesia, Federated States of",     "+691",     "FM"  },
                  new string  []  { "Moldova, Republic of",     "+373",     "MD"  },
                  new string  []  { "Mozambique",     "+258",     "MZ"  },
                  new string  []  { "Palestinian Territory, Occupied",     "+970",     "PS"  },
                  new string  []  { "Pitcairn",     "+872",     "PN"  },
                  new string  []  { "Réunion",     "+262",     "RE"  },
                  new string  []  { "Russia",     "+7",     "RU"  },
                  new string  []  { "Saint Barthélemy",     "+590",     "BL"  },
                  new string  []  { "Saint Helena, Ascension and Tristan Da Cunha",     "+290",     "SH"  },
                  new string  []  { "Saint Kitts and Nevis",     "+1 869",     "KN"  },
                  new string  []  { "Saint Lucia",     "+1 758",     "LC"  },
                  new string  []  { "Saint Martin",     "+590",     "MF"  },
                  new string  []  { "Saint Pierre and Miquelon",     "+508",     "PM"  },
                  new string  []  { "Saint Vincent and the Grenadines",     "+1 784",     "VC"  },
                  new string  []  { "Sao Tome and Principe",     "+239",     "ST"  },
                  new string  []  { "Somalia",     "+252",     "SO"  },
                  new string  []  { "Svalbard and Jan Mayen",     "+47",     "SJ"  },
                  new string  []  { "Syrian Arab Republic",     "+963",     "SY"  },
                  new string  []  { "Taiwan, Province of China",     "+886",     "TW"  },
                  new string  []  { "Tanzania, United Republic of",     "+255",     "TZ"  },
                  new string  []  { "Timor-Leste",     "+670",     "TL"  },
                  new string  []  { "Venezuela, Bolivarian Republic of",     "+58",     "VE"  },
                  new string  []  { "Viet Nam",     "+84",     "VN"  },
                  new string  []  { "Virgin Islands, British",     "+1 284",     "VG"  },
                  new string  []  { "Virgin Islands, U.S.",     "+1 340",     "VI"  }
            };
    }
}