//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAZT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GAZT.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear taxpayer, when calculating the
        ///
        ///amendments, found that your
        ///
        ///amendments do not match what was
        ///
        ///calculated by the General Authority
        ///
        ///for Zakat and Income, and in case of
        ///
        ///wants to continue will be created an
        ///
        ///appeal.
        /// </summary>
        public static string AmendmentsDoNotMatchText {
            get {
                return ResourceManager.GetString("AmendmentsDoNotMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amend Return.
        /// </summary>
        public static string AmendReturn {
            get {
                return ResourceManager.GetString("AmendReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount details and SADAD number payment.
        /// </summary>
        public static string AmountDetailsAndSADADNumberPayment {
            get {
                return ResourceManager.GetString("AmountDetailsAndSADADNumberPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount not objected.
        /// </summary>
        public static string AmountNotObjected {
            get {
                return ResourceManager.GetString("AmountNotObjected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditing.
        /// </summary>
        public static string Auditing {
            get {
                return ResourceManager.GetString("Auditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average number of employment.
        /// </summary>
        public static string AverageNumOfEmployment {
            get {
                return ResourceManager.GetString("AverageNumOfEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billed number.
        /// </summary>
        public static string BilledNumber {
            get {
                return ResourceManager.GetString("BilledNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital.
        /// </summary>
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatting.
        /// </summary>
        public static string Chatting {
            get {
                return ResourceManager.GetString("Chatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts to be approved.
        /// </summary>
        public static string ContractsToBeApproved {
            get {
                return ResourceManager.GetString("ContractsToBeApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has copied SADAD payment number.
        /// </summary>
        public static string CopiedSADADPaymentNumber {
            get {
                return ResourceManager.GetString("CopiedSADADPaymentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy SADAD number.
        /// </summary>
        public static string CopySADADNumber {
            get {
                return ResourceManager.GetString("CopySADADNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy SADAD payment number.
        /// </summary>
        public static string CopySADADPaymentNumber {
            get {
                return ResourceManager.GetString("CopySADADPaymentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data available to GAZT.
        /// </summary>
        public static string DataAvailableToGAZT {
            get {
                return ResourceManager.GetString("DataAvailableToGAZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date ( Hijri).
        /// </summary>
        public static string DateHijri {
            get {
                return ResourceManager.GetString("DateHijri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Changed Successfully.
        /// </summary>
        public static string DetailsChangedSuccessfully {
            get {
                return ResourceManager.GetString("DetailsChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of SADAD bill.
        /// </summary>
        public static string DetailsOfSADADBill {
            get {
                return ResourceManager.GetString("DetailsOfSADADBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Amount.
        /// </summary>
        public static string DueAmount {
            get {
                return ResourceManager.GetString("DueAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verification Code sent successfully.
        /// </summary>
        public static string Emailverificationcodesentsuccessfully {
            get {
                return ResourceManager.GetString("Emailverificationcodesentsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +966 enter your 9 digit mobile number.
        /// </summary>
        public static string EnterNewMobileNumber {
            get {
                return ResourceManager.GetString("EnterNewMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid mobile number.
        /// </summary>
        public static string EnterValidMobileNumber {
            get {
                return ResourceManager.GetString("EnterValidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter verification code received on mobile.
        /// </summary>
        public static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter verification code received on email.
        /// </summary>
        public static string EnterVerificationCodeForEmail {
            get {
                return ResourceManager.GetString("EnterVerificationCodeForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate sales for Fiscal year.
        /// </summary>
        public static string EstimateSalesForFiscalYear {
            get {
                return ResourceManager.GetString("EstimateSalesForFiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        public static string EstimateZakatReturn {
            get {
                return ResourceManager.GetString("EstimateZakatReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export value.
        /// </summary>
        public static string ExportValue {
            get {
                return ResourceManager.GetString("ExportValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal year.
        /// </summary>
        public static string FiscalYear {
            get {
                return ResourceManager.GetString("FiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import value.
        /// </summary>
        public static string ImportValue {
            get {
                return ResourceManager.GetString("ImportValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP, please enter correct OTP.
        /// </summary>
        public static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have paid {} SAR for current fiscal year.
        /// </summary>
        public static string ItHasPaidNumberForCurrentFiscalYear {
            get {
                return ResourceManager.GetString("ItHasPaidNumberForCurrentFiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful.
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log off?.
        /// </summary>
        public static string LogoutConfirmationMessage {
            get {
                return ResourceManager.GetString("LogoutConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is compulsory to change password.
        /// </summary>
        public static string MandatoryPasswordForEmailUpdatation {
            get {
                return ResourceManager.GetString("MandatoryPasswordForEmailUpdatation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number Updated Successfully.
        /// </summary>
        public static string MobileNumberUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MobileNumberUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number Verification Successful.
        /// </summary>
        public static string MobileNumberVerificationSuccessful {
            get {
                return ResourceManager.GetString("MobileNumberVerificationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Bills.
        /// </summary>
        public static string MyBills {
            get {
                return ResourceManager.GetString("MyBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Bills.
        /// </summary>
        public static string MyBillsInvoices {
            get {
                return ResourceManager.GetString("MyBillsInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Certificate.
        /// </summary>
        public static string MyCertificate {
            get {
                return ResourceManager.GetString("MyCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email address is not matching.
        /// </summary>
        public static string NewEmailandRetypeEmailNotMatch {
            get {
                return ResourceManager.GetString("NewEmailandRetypeEmailNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mobile Number.
        /// </summary>
        public static string NewMobileNumber {
            get {
                return ResourceManager.GetString("NewMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password field and Confirm Password field must match.
        /// </summary>
        public static string NewPasswordandRetypePasswordNotMatch {
            get {
                return ResourceManager.GetString("NewPasswordandRetypePasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Email.
        /// </summary>
        public static string OldEmail {
            get {
                return ResourceManager.GetString("OldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue Return.
        /// </summary>
        public static string OverdueReturn {
            get {
                return ResourceManager.GetString("OverdueReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially Paid.
        /// </summary>
        public static string PartiallyPaid {
            get {
                return ResourceManager.GetString("PartiallyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Password .
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Sucessfully .
        /// </summary>
        public static string PassWordChangedSucessfully {
            get {
                return ResourceManager.GetString("PassWordChangedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay by MADA.
        /// </summary>
        public static string PayByMADA {
            get {
                return ResourceManager.GetString("PayByMADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf.
        /// </summary>
        public static string Pdf {
            get {
                return ResourceManager.GetString("Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Certificate Available.
        /// </summary>
        public static string PdfIsNoteAvailable {
            get {
                return ResourceManager.GetString("PdfIsNoteAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-verify.
        /// </summary>
        public static string PleaseReVerify {
            get {
                return ResourceManager.GetString("PleaseReVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Value.
        /// </summary>
        public static string PurchaseValue {
            get {
                return ResourceManager.GetString("PurchaseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for chatting.
        /// </summary>
        public static string ReasonForChatting {
            get {
                return ResourceManager.GetString("ReasonForChatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason of amend.
        /// </summary>
        public static string ReasonOfAmend {
            get {
                return ResourceManager.GetString("ReasonOfAmend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration certificate.
        /// </summary>
        public static string RegistrationCertificate {
            get {
                return ResourceManager.GetString("RegistrationCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Period.
        /// </summary>
        public static string ReturnPeriod {
            get {
                return ResourceManager.GetString("ReturnPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Email.
        /// </summary>
        public static string RetypeEmail {
            get {
                return ResourceManager.GetString("RetypeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Password.
        /// </summary>
        public static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SADAD number.
        /// </summary>
        public static string SADADNumber {
            get {
                return ResourceManager.GetString("SADADNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SADAD Payment Number.
        /// </summary>
        public static string SADADPaymentNumber {
            get {
                return ResourceManager.GetString("SADADPaymentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Details.
        /// </summary>
        public static string SalesDetails {
            get {
                return ResourceManager.GetString("SalesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales not sales points.
        /// </summary>
        public static string SalesNotSalesPoints {
            get {
                return ResourceManager.GetString("SalesNotSalesPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Chatting.
        /// </summary>
        public static string StartChatting {
            get {
                return ResourceManager.GetString("StartChatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted Return.
        /// </summary>
        public static string SubmittedReturn {
            get {
                return ResourceManager.GetString("SubmittedReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of Zakat Calculation.
        /// </summary>
        public static string SummaryOfZakatCalculation {
            get {
                return ResourceManager.GetString("SummaryOfZakatCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxpayer Profile.
        /// </summary>
        public static string TaxpayerProfile {
            get {
                return ResourceManager.GetString("TaxpayerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  TIN .
        /// </summary>
        public static string TIN {
            get {
                return ResourceManager.GetString("TIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIN-Email.
        /// </summary>
        public static string TinEmail {
            get {
                return ResourceManager.GetString("TinEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of the Bills Unpaid.
        /// </summary>
        public static string TotalOfBillsUnpaid {
            get {
                return ResourceManager.GetString("TotalOfBillsUnpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total required to be paid.
        /// </summary>
        public static string TotalRequiredToBePaid {
            get {
                return ResourceManager.GetString("TotalRequiredToBePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25% from  objected amount.
        /// </summary>
        public static string TwentyFivePercentageObjectedAmount {
            get {
                return ResourceManager.GetString("TwentyFivePercentageObjectedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        public static string Unpaid {
            get {
                return ResourceManager.GetString("Unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account locked.
        /// </summary>
        public static string UserAccountLocked {
            get {
                return ResourceManager.GetString("UserAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  User authentication failed.
        /// </summary>
        public static string UserAuthenticationFailed {
            get {
                return ResourceManager.GetString("UserAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Registration Certificate.
        /// </summary>
        public static string VATRegistrationCertificate {
            get {
                return ResourceManager.GetString("VATRegistrationCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakat Amount.
        /// </summary>
        public static string ZakatAmount {
            get {
                return ResourceManager.GetString("ZakatAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakat Base.
        /// </summary>
        public static string ZakatBase {
            get {
                return ResourceManager.GetString("ZakatBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An appeal will not be filed only in case pay for Amount not objected plus 25% from objected amount. In case accepted in whole or in part objection. It will refunded to the amount objected.
        /// </summary>
        public static string ZakatTaxType {
            get {
                return ResourceManager.GetString("ZakatTaxType", resourceCulture);
            }
        }
    }
}
