//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAZT {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GAZT.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        public static string AmendReturn {
            get {
                return ResourceManager.GetString("AmendReturn", resourceCulture);
            }
        }
        
        public static string AmountDetailsAndSADADNumberPayment {
            get {
                return ResourceManager.GetString("AmountDetailsAndSADADNumberPayment", resourceCulture);
            }
        }
        
        public static string AmountNotObjected {
            get {
                return ResourceManager.GetString("AmountNotObjected", resourceCulture);
            }
        }
        
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        public static string Auditing {
            get {
                return ResourceManager.GetString("Auditing", resourceCulture);
            }
        }
        
        public static string AverageNumOfEmployment {
            get {
                return ResourceManager.GetString("AverageNumOfEmployment", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        public static string BilledNumber {
            get {
                return ResourceManager.GetString("BilledNumber", resourceCulture);
            }
        }
        
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        public static string Chatting {
            get {
                return ResourceManager.GetString("Chatting", resourceCulture);
            }
        }
        
        public static string ContractsToBeApproved {
            get {
                return ResourceManager.GetString("ContractsToBeApproved", resourceCulture);
            }
        }
        
        public static string CopiedSADADPaymentNumber {
            get {
                return ResourceManager.GetString("CopiedSADADPaymentNumber", resourceCulture);
            }
        }
        
        public static string CopySADADNumber {
            get {
                return ResourceManager.GetString("CopySADADNumber", resourceCulture);
            }
        }
        
        public static string CopySADADPaymentNumber {
            get {
                return ResourceManager.GetString("CopySADADPaymentNumber", resourceCulture);
            }
        }
        
        public static string DataAvailableToGAZT {
            get {
                return ResourceManager.GetString("DataAvailableToGAZT", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string DateHijri {
            get {
                return ResourceManager.GetString("DateHijri", resourceCulture);
            }
        }
        
        public static string DetailsOfSADADBill {
            get {
                return ResourceManager.GetString("DetailsOfSADADBill", resourceCulture);
            }
        }
        
        public static string DueAmount {
            get {
                return ResourceManager.GetString("DueAmount", resourceCulture);
            }
        }
        
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string OldEmail {
            get {
                return ResourceManager.GetString("OldEmail", resourceCulture);
            }
        }
        
        public static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        public static string EstimateSalesForFiscalYear {
            get {
                return ResourceManager.GetString("EstimateSalesForFiscalYear", resourceCulture);
            }
        }
        
        public static string EstimateZakatReturn {
            get {
                return ResourceManager.GetString("EstimateZakatReturn", resourceCulture);
            }
        }
        
        public static string ExportValue {
            get {
                return ResourceManager.GetString("ExportValue", resourceCulture);
            }
        }
        
        public static string FiscalYear {
            get {
                return ResourceManager.GetString("FiscalYear", resourceCulture);
            }
        }
        
        public static string ImportValue {
            get {
                return ResourceManager.GetString("ImportValue", resourceCulture);
            }
        }
        
        public static string ItHasPaidNumberForCurrentFiscalYear {
            get {
                return ResourceManager.GetString("ItHasPaidNumberForCurrentFiscalYear", resourceCulture);
            }
        }
        
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        public static string MyBills {
            get {
                return ResourceManager.GetString("MyBills", resourceCulture);
            }
        }
        
        public static string MyBillsInvoices {
            get {
                return ResourceManager.GetString("MyBillsInvoices", resourceCulture);
            }
        }
        
        public static string MyCertificate {
            get {
                return ResourceManager.GetString("MyCertificate", resourceCulture);
            }
        }
        
        public static string VATCertificates {
            get {
                return ResourceManager.GetString("VATCertificates", resourceCulture);
            }
        }
        
        public static string ZakatCertificates {
            get {
                return ResourceManager.GetString("ZakatCertificates", resourceCulture);
            }
        }
        
        public static string ExciseCertificates {
            get {
                return ResourceManager.GetString("ExciseCertificates", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        public static string NewMobileNumber {
            get {
                return ResourceManager.GetString("NewMobileNumber", resourceCulture);
            }
        }
        
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        public static string OverdueReturn {
            get {
                return ResourceManager.GetString("OverdueReturn", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        public static string PayByMADA {
            get {
                return ResourceManager.GetString("PayByMADA", resourceCulture);
            }
        }
        
        public static string PurchaseValue {
            get {
                return ResourceManager.GetString("PurchaseValue", resourceCulture);
            }
        }
        
        public static string ReasonForChatting {
            get {
                return ResourceManager.GetString("ReasonForChatting", resourceCulture);
            }
        }
        
        public static string ReasonOfAmend {
            get {
                return ResourceManager.GetString("ReasonOfAmend", resourceCulture);
            }
        }
        
        public static string RegistrationCertificate {
            get {
                return ResourceManager.GetString("RegistrationCertificate", resourceCulture);
            }
        }
        
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        public static string ReturnPeriod {
            get {
                return ResourceManager.GetString("ReturnPeriod", resourceCulture);
            }
        }
        
        public static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        public static string RetypeEmail {
            get {
                return ResourceManager.GetString("RetypeEmail", resourceCulture);
            }
        }
        
        public static string SADADNumber {
            get {
                return ResourceManager.GetString("SADADNumber", resourceCulture);
            }
        }
        
        public static string SADADPaymentNumber {
            get {
                return ResourceManager.GetString("SADADPaymentNumber", resourceCulture);
            }
        }
        
        public static string SalesDetails {
            get {
                return ResourceManager.GetString("SalesDetails", resourceCulture);
            }
        }
        
        public static string SalesNotSalesPoints {
            get {
                return ResourceManager.GetString("SalesNotSalesPoints", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string StartChatting {
            get {
                return ResourceManager.GetString("StartChatting", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string SubmittedReturn {
            get {
                return ResourceManager.GetString("SubmittedReturn", resourceCulture);
            }
        }
        
        public static string SummaryOfZakatCalculation {
            get {
                return ResourceManager.GetString("SummaryOfZakatCalculation", resourceCulture);
            }
        }
        
        public static string TaxpayerProfile {
            get {
                return ResourceManager.GetString("TaxpayerProfile", resourceCulture);
            }
        }
        
        public static string TIN {
            get {
                return ResourceManager.GetString("TIN", resourceCulture);
            }
        }
        
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        public static string TotalOfBillsUnpaid {
            get {
                return ResourceManager.GetString("TotalOfBillsUnpaid", resourceCulture);
            }
        }
        
        public static string TotalRequiredToBePaid {
            get {
                return ResourceManager.GetString("TotalRequiredToBePaid", resourceCulture);
            }
        }
        
        public static string TwentyFivePercentageObjectedAmount {
            get {
                return ResourceManager.GetString("TwentyFivePercentageObjectedAmount", resourceCulture);
            }
        }
        
        public static string VATRegistrationCertificate {
            get {
                return ResourceManager.GetString("VATRegistrationCertificate", resourceCulture);
            }
        }
        
        public static string ZakatAmount {
            get {
                return ResourceManager.GetString("ZakatAmount", resourceCulture);
            }
        }
        
        public static string ZakatBase {
            get {
                return ResourceManager.GetString("ZakatBase", resourceCulture);
            }
        }
        
        public static string ZakatTaxType {
            get {
                return ResourceManager.GetString("ZakatTaxType", resourceCulture);
            }
        }
        
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        public static string AmendmentsDoNotMatchText {
            get {
                return ResourceManager.GetString("AmendmentsDoNotMatchText", resourceCulture);
            }
        }
        
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        public static string MobileNumberVerificationSuccessful {
            get {
                return ResourceManager.GetString("MobileNumberVerificationSuccessful", resourceCulture);
            }
        }
        
        public static string PassWordChangedSucessfully {
            get {
                return ResourceManager.GetString("PassWordChangedSucessfully", resourceCulture);
            }
        }
        
        public static string PdfIsNoteAvailable {
            get {
                return ResourceManager.GetString("PdfIsNoteAvailable", resourceCulture);
            }
        }
        
        public static string TinEmail {
            get {
                return ResourceManager.GetString("TinEmail", resourceCulture);
            }
        }
        
        public static string MobileNumberUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MobileNumberUpdatedSuccessfully", resourceCulture);
            }
        }
        
        public static string DetailsChangedSuccessfully {
            get {
                return ResourceManager.GetString("DetailsChangedSuccessfully", resourceCulture);
            }
        }
        
        public static string Emailverificationcodesentsuccessfully {
            get {
                return ResourceManager.GetString("Emailverificationcodesentsuccessfully", resourceCulture);
            }
        }
        
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        public static string LogoutConfirmationMessage {
            get {
                return ResourceManager.GetString("LogoutConfirmationMessage", resourceCulture);
            }
        }
        
        public static string NewEmailandRetypeEmailNotMatch {
            get {
                return ResourceManager.GetString("NewEmailandRetypeEmailNotMatch", resourceCulture);
            }
        }
        
        public static string NewPasswordandRetypePasswordNotMatch {
            get {
                return ResourceManager.GetString("NewPasswordandRetypePasswordNotMatch", resourceCulture);
            }
        }
        
        public static string EnterVerificationCodeForEmail {
            get {
                return ResourceManager.GetString("EnterVerificationCodeForEmail", resourceCulture);
            }
        }
        
        public static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        public static string EnterNewMobileNumber {
            get {
                return ResourceManager.GetString("EnterNewMobileNumber", resourceCulture);
            }
        }
        
        public static string EnterValidMobileNumber {
            get {
                return ResourceManager.GetString("EnterValidMobileNumber", resourceCulture);
            }
        }
        
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        public static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        public static string UserAuthenticationFailed {
            get {
                return ResourceManager.GetString("UserAuthenticationFailed", resourceCulture);
            }
        }
        
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        public static string UserAccountLocked {
            get {
                return ResourceManager.GetString("UserAccountLocked", resourceCulture);
            }
        }
        
        public static string PleaseReVerify {
            get {
                return ResourceManager.GetString("PleaseReVerify", resourceCulture);
            }
        }
        
        public static string MandatoryPasswordForEmailUpdatation {
            get {
                return ResourceManager.GetString("MandatoryPasswordForEmailUpdatation", resourceCulture);
            }
        }
        
        public static string TINS {
            get {
                return ResourceManager.GetString("TINS", resourceCulture);
            }
        }
        
        public static string NoTINsAvailable {
            get {
                return ResourceManager.GetString("NoTINsAvailable", resourceCulture);
            }
        }
        
        public static string NetworkConnectivityIssue {
            get {
                return ResourceManager.GetString("NetworkConnectivityIssue", resourceCulture);
            }
        }
        
        public static string ForgotPasswordORUseName {
            get {
                return ResourceManager.GetString("ForgotPasswordORUseName", resourceCulture);
            }
        }
        
        public static string Individual {
            get {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }
        
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        public static string ForgotUsername {
            get {
                return ResourceManager.GetString("ForgotUsername", resourceCulture);
            }
        }
        
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        public static string NationaID {
            get {
                return ResourceManager.GetString("NationaID", resourceCulture);
            }
        }
        
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        public static string SelectPasswordUserName {
            get {
                return ResourceManager.GetString("SelectPasswordUserName", resourceCulture);
            }
        }
        
        public static string EntityType {
            get {
                return ResourceManager.GetString("EntityType", resourceCulture);
            }
        }
        
        public static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        public static string IDType {
            get {
                return ResourceManager.GetString("IDType", resourceCulture);
            }
        }
        
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        public static string CorportaeID {
            get {
                return ResourceManager.GetString("CorportaeID", resourceCulture);
            }
        }
        
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        public static string PaymentNumber {
            get {
                return ResourceManager.GetString("PaymentNumber", resourceCulture);
            }
        }
        
        public static string Sadad {
            get {
                return ResourceManager.GetString("Sadad", resourceCulture);
            }
        }
        
        public static string SadadPaymentNumberForBills {
            get {
                return ResourceManager.GetString("SadadPaymentNumberForBills", resourceCulture);
            }
        }
        
        public static string ZakatTaxTypeForBills {
            get {
                return ResourceManager.GetString("ZakatTaxTypeForBills", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        public static string PartiallyPaid {
            get {
                return ResourceManager.GetString("PartiallyPaid", resourceCulture);
            }
        }
        
        public static string UnPaid {
            get {
                return ResourceManager.GetString("UnPaid", resourceCulture);
            }
        }
        
        public static string ForgotPasswordOrUserName {
            get {
                return ResourceManager.GetString("ForgotPasswordOrUserName", resourceCulture);
            }
        }
        
        public static string InvaliedCaptcha {
            get {
                return ResourceManager.GetString("InvaliedCaptcha", resourceCulture);
            }
        }
        
        public static string NoBillsAvailable {
            get {
                return ResourceManager.GetString("NoBillsAvailable", resourceCulture);
            }
        }
        
        public static string ActivityIndicatorTitle {
            get {
                return ResourceManager.GetString("ActivityIndicatorTitle", resourceCulture);
            }
        }
        
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        public static string EnterNewpassword {
            get {
                return ResourceManager.GetString("EnterNewpassword", resourceCulture);
            }
        }
        
        public static string EnterConfirmpassword {
            get {
                return ResourceManager.GetString("EnterConfirmpassword", resourceCulture);
            }
        }
        
        public static string EnterOTP {
            get {
                return ResourceManager.GetString("EnterOTP", resourceCulture);
            }
        }
        
        public static string ResendOTP {
            get {
                return ResourceManager.GetString("ResendOTP", resourceCulture);
            }
        }
        
        public static string PleaseenterUsername {
            get {
                return ResourceManager.GetString("PleaseenterUsername", resourceCulture);
            }
        }
        
        public static string enteredcaptchacodeisincorrect {
            get {
                return ResourceManager.GetString("enteredcaptchacodeisincorrect", resourceCulture);
            }
        }
        
        public static string Somethingwentwrong {
            get {
                return ResourceManager.GetString("Somethingwentwrong", resourceCulture);
            }
        }
        
        public static string Pleasechangepassword {
            get {
                return ResourceManager.GetString("Pleasechangepassword", resourceCulture);
            }
        }
        
        public static string Invalidverificationcodeentered {
            get {
                return ResourceManager.GetString("Invalidverificationcodeentered", resourceCulture);
            }
        }
        
        public static string PleaseenterOTP {
            get {
                return ResourceManager.GetString("PleaseenterOTP", resourceCulture);
            }
        }
        
        public static string Usernamehasbeensenttoregisteredmobilenumber {
            get {
                return ResourceManager.GetString("Usernamehasbeensenttoregisteredmobilenumber", resourceCulture);
            }
        }
        
        public static string YourPasswordhasbeenChangedsuccessfully {
            get {
                return ResourceManager.GetString("YourPasswordhasbeenChangedsuccessfully", resourceCulture);
            }
        }
        
        public static string Boththepasswordfieldsshouldmatch {
            get {
                return ResourceManager.GetString("Boththepasswordfieldsshouldmatch", resourceCulture);
            }
        }
        
        public static string PasswordValidationMesseg {
            get {
                return ResourceManager.GetString("PasswordValidationMesseg", resourceCulture);
            }
        }
        
        public static string Dashoboard {
            get {
                return ResourceManager.GetString("Dashoboard", resourceCulture);
            }
        }
        
        public static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
        
        public static string Correspondance {
            get {
                return ResourceManager.GetString("Correspondance", resourceCulture);
            }
        }
        
        public static string EServices {
            get {
                return ResourceManager.GetString("EServices", resourceCulture);
            }
        }
        
        public static string EstimateZakat {
            get {
                return ResourceManager.GetString("EstimateZakat", resourceCulture);
            }
        }
        
        public static string NonSubmitted {
            get {
                return ResourceManager.GetString("NonSubmitted", resourceCulture);
            }
        }
        
        public static string OverDue {
            get {
                return ResourceManager.GetString("OverDue", resourceCulture);
            }
        }
        
        public static string Partial {
            get {
                return ResourceManager.GetString("Partial", resourceCulture);
            }
        }
        
        public static string Returns {
            get {
                return ResourceManager.GetString("Returns", resourceCulture);
            }
        }
        
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        public static string VATDeclaration {
            get {
                return ResourceManager.GetString("VATDeclaration", resourceCulture);
            }
        }
        
        public static string TotalUnpaidBills {
            get {
                return ResourceManager.GetString("TotalUnpaidBills", resourceCulture);
            }
        }
        
        public static string TotalUnpaidBillsAmount {
            get {
                return ResourceManager.GetString("TotalUnpaidBillsAmount", resourceCulture);
            }
        }
        
        public static string TotalPartiallyPaidBills {
            get {
                return ResourceManager.GetString("TotalPartiallyPaidBills", resourceCulture);
            }
        }
        
        public static string TotalPartialPaidBillsAmount {
            get {
                return ResourceManager.GetString("TotalPartialPaidBillsAmount", resourceCulture);
            }
        }
        
        public static string Nodataavailable {
            get {
                return ResourceManager.GetString("Nodataavailable", resourceCulture);
            }
        }
        
        public static string Entercaptcha {
            get {
                return ResourceManager.GetString("Entercaptcha", resourceCulture);
            }
        }
        
        public static string EnterId {
            get {
                return ResourceManager.GetString("EnterId", resourceCulture);
            }
        }
        
        public static string Enterusername {
            get {
                return ResourceManager.GetString("Enterusername", resourceCulture);
            }
        }
        
        public static string ResendVerificationCode {
            get {
                return ResourceManager.GetString("ResendVerificationCode", resourceCulture);
            }
        }
        
        public static string PleaseEnterverificationcodereceivedonmobiletoEnterGAZTPortal {
            get {
                return ResourceManager.GetString("PleaseEnterverificationcodereceivedonmobiletoEnterGAZTPortal", resourceCulture);
            }
        }
        
        public static string TheaccountwillbelockedafterThreefailedverificationcodeattempts {
            get {
                return ResourceManager.GetString("TheaccountwillbelockedafterThreefailedverificationcodeattempts", resourceCulture);
            }
        }
        
        public static string Clickhereforlogin {
            get {
                return ResourceManager.GetString("Clickhereforlogin", resourceCulture);
            }
        }
        
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        public static string VarificationCode {
            get {
                return ResourceManager.GetString("VarificationCode", resourceCulture);
            }
        }
        
        public static string VATLookup {
            get {
                return ResourceManager.GetString("VATLookup", resourceCulture);
            }
        }
        
        public static string TotalSubmittedReturns {
            get {
                return ResourceManager.GetString("TotalSubmittedReturns", resourceCulture);
            }
        }
        
        public static string TotalPaidReturns {
            get {
                return ResourceManager.GetString("TotalPaidReturns", resourceCulture);
            }
        }
        
        public static string TotalOverDueReturns {
            get {
                return ResourceManager.GetString("TotalOverDueReturns", resourceCulture);
            }
        }
        
        public static string TotalPaidBills {
            get {
                return ResourceManager.GetString("TotalPaidBills", resourceCulture);
            }
        }
        
        public static string TotalNonSubmittedReturns {
            get {
                return ResourceManager.GetString("TotalNonSubmittedReturns", resourceCulture);
            }
        }
        
        public static string TotalNoofReturns {
            get {
                return ResourceManager.GetString("TotalNoofReturns", resourceCulture);
            }
        }
        
        public static string TotalPaidBillsAmount {
            get {
                return ResourceManager.GetString("TotalPaidBillsAmount", resourceCulture);
            }
        }
        
        public static string TotalPartiallyPaidReturns {
            get {
                return ResourceManager.GetString("TotalPartiallyPaidReturns", resourceCulture);
            }
        }
        
        public static string TotalUnpaidReturns {
            get {
                return ResourceManager.GetString("TotalUnpaidReturns", resourceCulture);
            }
        }
        
        public static string TheAccountwillbelockedwithinTwomin {
            get {
                return ResourceManager.GetString("TheAccountwillbelockedwithinTwomin", resourceCulture);
            }
        }
        
        public static string TheAccountWillBeLockedAfterThreeAttempts {
            get {
                return ResourceManager.GetString("TheAccountWillBeLockedAfterThreeAttempts", resourceCulture);
            }
        }
        
        public static string PasswordGuidelineText {
            get {
                return ResourceManager.GetString("PasswordGuidelineText", resourceCulture);
            }
        }
        
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        public static string ChangeMobileNumber {
            get {
                return ResourceManager.GetString("ChangeMobileNumber", resourceCulture);
            }
        }
        
        public static string TaxType {
            get {
                return ResourceManager.GetString("TaxType", resourceCulture);
            }
        }
        
        public static string ZPleaseEnterAValidUserID {
            get {
                return ResourceManager.GetString("ZPleaseEnterAValidUserID", resourceCulture);
            }
        }
        
        public static string ZFicalYear {
            get {
                return ResourceManager.GetString("ZFicalYear", resourceCulture);
            }
        }
        
        public static string ZAccountLocked {
            get {
                return ResourceManager.GetString("ZAccountLocked", resourceCulture);
            }
        }
        
        public static string ZLogoff {
            get {
                return ResourceManager.GetString("ZLogoff", resourceCulture);
            }
        }
        
        public static string ZPasswordLocked {
            get {
                return ResourceManager.GetString("ZPasswordLocked", resourceCulture);
            }
        }
        
        public static string ZSAR {
            get {
                return ResourceManager.GetString("ZSAR", resourceCulture);
            }
        }
        
        public static string ZTotalPaidAmount {
            get {
                return ResourceManager.GetString("ZTotalPaidAmount", resourceCulture);
            }
        }
        
        public static string ZTotalUnPaidAmount {
            get {
                return ResourceManager.GetString("ZTotalUnPaidAmount", resourceCulture);
            }
        }
        
        public static string ZUserNotValid {
            get {
                return ResourceManager.GetString("ZUserNotValid", resourceCulture);
            }
        }
        
        public static string ZYourSessionhasexpiredPleaseLoginagain {
            get {
                return ResourceManager.GetString("ZYourSessionhasexpiredPleaseLoginagain", resourceCulture);
            }
        }
        
        public static string ZLogout {
            get {
                return ResourceManager.GetString("ZLogout", resourceCulture);
            }
        }
        
        public static string ZEntertherequiredfield {
            get {
                return ResourceManager.GetString("ZEntertherequiredfield", resourceCulture);
            }
        }
        
        public static string ZError {
            get {
                return ResourceManager.GetString("ZError", resourceCulture);
            }
        }
        
        public static string ZYouhaveoneremainingattemptthentheaccountwillbelocked {
            get {
                return ResourceManager.GetString("ZYouhaveoneremainingattemptthentheaccountwillbelocked", resourceCulture);
            }
        }
        
        public static string ZYouraccounthasbeenlockedPleasecontactourcallcenter {
            get {
                return ResourceManager.GetString("ZYouraccounthasbeenlockedPleasecontactourcallcenter", resourceCulture);
            }
        }
        
        public static string ZSadadInvoiceNumber {
            get {
                return ResourceManager.GetString("ZSadadInvoiceNumber", resourceCulture);
            }
        }
        
        public static string ZUserNameIncorrect {
            get {
                return ResourceManager.GetString("ZUserNameIncorrect", resourceCulture);
            }
        }
        
        public static string Pleaseenteryourlogininformation {
            get {
                return ResourceManager.GetString("Pleaseenteryourlogininformation", resourceCulture);
            }
        }
        
        public static string ZEmailUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ZEmailUpdatedSuccessfully", resourceCulture);
            }
        }
        
        public static string ZNo {
            get {
                return ResourceManager.GetString("ZNo", resourceCulture);
            }
        }
        
        public static string ZYes {
            get {
                return ResourceManager.GetString("ZYes", resourceCulture);
            }
        }
        
        public static string ZCRNumber {
            get {
                return ResourceManager.GetString("ZCRNumber", resourceCulture);
            }
        }
        
        public static string ZCRNumberisnotequalto10 {
            get {
                return ResourceManager.GetString("ZCRNumberisnotequalto10", resourceCulture);
            }
        }
        
        public static string ZPleaseenterlookupnumber {
            get {
                return ResourceManager.GetString("ZPleaseenterlookupnumber", resourceCulture);
            }
        }
        
        public static string ZPleaseenterthecorrespondingnumber {
            get {
                return ResourceManager.GetString("ZPleaseenterthecorrespondingnumber", resourceCulture);
            }
        }
        
        public static string ZPleaseentertheCRcomposedof10digits {
            get {
                return ResourceManager.GetString("ZPleaseentertheCRcomposedof10digits", resourceCulture);
            }
        }
        
        public static string ZPleaseentertheVATAccountNocomposedof15digits {
            get {
                return ResourceManager.GetString("ZPleaseentertheVATAccountNocomposedof15digits", resourceCulture);
            }
        }
        
        public static string ZPleaseselectparametertype {
            get {
                return ResourceManager.GetString("ZPleaseselectparametertype", resourceCulture);
            }
        }
        
        public static string ZSearchParameter {
            get {
                return ResourceManager.GetString("ZSearchParameter", resourceCulture);
            }
        }
        
        public static string ZVATAccountNumber {
            get {
                return ResourceManager.GetString("ZVATAccountNumber", resourceCulture);
            }
        }
        
        public static string ZVATCerNumberisnotequalto15 {
            get {
                return ResourceManager.GetString("ZVATCerNumberisnotequalto15", resourceCulture);
            }
        }
        
        public static string ZVATCertificateNumber {
            get {
                return ResourceManager.GetString("ZVATCertificateNumber", resourceCulture);
            }
        }
        
        public static string ZVATLookupDialogue {
            get {
                return ResourceManager.GetString("ZVATLookupDialogue", resourceCulture);
            }
        }
        
        public static string ZVATNumberisnotequalto15 {
            get {
                return ResourceManager.GetString("ZVATNumberisnotequalto15", resourceCulture);
            }
        }
        
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        public static string EnterVerificationCodeTitle {
            get {
                return ResourceManager.GetString("EnterVerificationCodeTitle", resourceCulture);
            }
        }
        
        public static string ZZakatReturnListing {
            get {
                return ResourceManager.GetString("ZZakatReturnListing", resourceCulture);
            }
        }
        
        public static string ZZakatReturnDetails {
            get {
                return ResourceManager.GetString("ZZakatReturnDetails", resourceCulture);
            }
        }
        
        public static string YMandatorydatanotentered {
            get {
                return ResourceManager.GetString("YMandatorydatanotentered", resourceCulture);
            }
        }
    }
}
