//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAZT {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GAZT.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string AmendReturn {
            get {
                return ResourceManager.GetString("AmendReturn", resourceCulture);
            }
        }
        
        public static string AmountDetailsAndSADADNumberPayment {
            get {
                return ResourceManager.GetString("AmountDetailsAndSADADNumberPayment", resourceCulture);
            }
        }
        
        public static string AmountNotObjected {
            get {
                return ResourceManager.GetString("AmountNotObjected", resourceCulture);
            }
        }
        
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        public static string Auditing {
            get {
                return ResourceManager.GetString("Auditing", resourceCulture);
            }
        }
        
        public static string AverageNumOfEmployment {
            get {
                return ResourceManager.GetString("AverageNumOfEmployment", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        public static string BilledNumber {
            get {
                return ResourceManager.GetString("BilledNumber", resourceCulture);
            }
        }
        
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        public static string Chatting {
            get {
                return ResourceManager.GetString("Chatting", resourceCulture);
            }
        }
        
        public static string ContractsToBeApproved {
            get {
                return ResourceManager.GetString("ContractsToBeApproved", resourceCulture);
            }
        }
        
        public static string CopiedSADADPaymentNumber {
            get {
                return ResourceManager.GetString("CopiedSADADPaymentNumber", resourceCulture);
            }
        }
        
        public static string CopySADADNumber {
            get {
                return ResourceManager.GetString("CopySADADNumber", resourceCulture);
            }
        }
        
        public static string CopySADADPaymentNumber {
            get {
                return ResourceManager.GetString("CopySADADPaymentNumber", resourceCulture);
            }
        }
        
        public static string DataAvailableToGAZT {
            get {
                return ResourceManager.GetString("DataAvailableToGAZT", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string DateHijri {
            get {
                return ResourceManager.GetString("DateHijri", resourceCulture);
            }
        }
        
        public static string DetailsOfSADADBill {
            get {
                return ResourceManager.GetString("DetailsOfSADADBill", resourceCulture);
            }
        }
        
        public static string DueAmount {
            get {
                return ResourceManager.GetString("DueAmount", resourceCulture);
            }
        }
        
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string OldEmail {
            get {
                return ResourceManager.GetString("OldEmail", resourceCulture);
            }
        }
        
        public static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        public static string EstimateSalesForFiscalYear {
            get {
                return ResourceManager.GetString("EstimateSalesForFiscalYear", resourceCulture);
            }
        }
        
        public static string EstimateZakatReturn {
            get {
                return ResourceManager.GetString("EstimateZakatReturn", resourceCulture);
            }
        }
        
        public static string ExportValue {
            get {
                return ResourceManager.GetString("ExportValue", resourceCulture);
            }
        }
        
        public static string FiscalYear {
            get {
                return ResourceManager.GetString("FiscalYear", resourceCulture);
            }
        }
        
        public static string ImportValue {
            get {
                return ResourceManager.GetString("ImportValue", resourceCulture);
            }
        }
        
        public static string ItHasPaidNumberForCurrentFiscalYear {
            get {
                return ResourceManager.GetString("ItHasPaidNumberForCurrentFiscalYear", resourceCulture);
            }
        }
        
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        public static string MyBills {
            get {
                return ResourceManager.GetString("MyBills", resourceCulture);
            }
        }
        
        public static string MyBillsInvoices {
            get {
                return ResourceManager.GetString("MyBillsInvoices", resourceCulture);
            }
        }
        
        public static string MyCertificate {
            get {
                return ResourceManager.GetString("MyCertificate", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        public static string NewMobileNumber {
            get {
                return ResourceManager.GetString("NewMobileNumber", resourceCulture);
            }
        }
        
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        public static string OverdueReturn {
            get {
                return ResourceManager.GetString("OverdueReturn", resourceCulture);
            }
        }
        
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        public static string PartiallyPaid {
            get {
                return ResourceManager.GetString("PartiallyPaid", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        public static string ChnagePassword {
            get {
                return ResourceManager.GetString("ChnagePassword", resourceCulture);
            }
        }
        
        public static string PayByMADA {
            get {
                return ResourceManager.GetString("PayByMADA", resourceCulture);
            }
        }
        
        public static string PurchaseValue {
            get {
                return ResourceManager.GetString("PurchaseValue", resourceCulture);
            }
        }
        
        public static string ReasonForChatting {
            get {
                return ResourceManager.GetString("ReasonForChatting", resourceCulture);
            }
        }
        
        public static string ReasonOfAmend {
            get {
                return ResourceManager.GetString("ReasonOfAmend", resourceCulture);
            }
        }
        
        public static string RegistrationCertificate {
            get {
                return ResourceManager.GetString("RegistrationCertificate", resourceCulture);
            }
        }
        
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        public static string ReturnPeriod {
            get {
                return ResourceManager.GetString("ReturnPeriod", resourceCulture);
            }
        }
        
        public static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        public static string RetypeEmail {
            get {
                return ResourceManager.GetString("RetypeEmail", resourceCulture);
            }
        }
        
        public static string SADADNumber {
            get {
                return ResourceManager.GetString("SADADNumber", resourceCulture);
            }
        }
        
        public static string SADADPaymentNumber {
            get {
                return ResourceManager.GetString("SADADPaymentNumber", resourceCulture);
            }
        }
        
        public static string SalesDetails {
            get {
                return ResourceManager.GetString("SalesDetails", resourceCulture);
            }
        }
        
        public static string SalesNotSalesPoints {
            get {
                return ResourceManager.GetString("SalesNotSalesPoints", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string StartChatting {
            get {
                return ResourceManager.GetString("StartChatting", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string SubmittedReturn {
            get {
                return ResourceManager.GetString("SubmittedReturn", resourceCulture);
            }
        }
        
        public static string SummaryOfZakatCalculation {
            get {
                return ResourceManager.GetString("SummaryOfZakatCalculation", resourceCulture);
            }
        }
        
        public static string TaxpayerProfile {
            get {
                return ResourceManager.GetString("TaxpayerProfile", resourceCulture);
            }
        }
        
        public static string TIN {
            get {
                return ResourceManager.GetString("TIN", resourceCulture);
            }
        }
        
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        public static string TotalOfBillsUnpaid {
            get {
                return ResourceManager.GetString("TotalOfBillsUnpaid", resourceCulture);
            }
        }
        
        public static string TotalRequiredToBePaid {
            get {
                return ResourceManager.GetString("TotalRequiredToBePaid", resourceCulture);
            }
        }
        
        public static string TwentyFivePercentageObjectedAmount {
            get {
                return ResourceManager.GetString("TwentyFivePercentageObjectedAmount", resourceCulture);
            }
        }
        
        public static string Unpaid {
            get {
                return ResourceManager.GetString("Unpaid", resourceCulture);
            }
        }
        
        public static string VATRegistrationCertificate {
            get {
                return ResourceManager.GetString("VATRegistrationCertificate", resourceCulture);
            }
        }
        
        public static string ZakatAmount {
            get {
                return ResourceManager.GetString("ZakatAmount", resourceCulture);
            }
        }
        
        public static string ZakatBase {
            get {
                return ResourceManager.GetString("ZakatBase", resourceCulture);
            }
        }
        
        public static string ZakatTaxType {
            get {
                return ResourceManager.GetString("ZakatTaxType", resourceCulture);
            }
        }
        
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        public static string AmendmentsDoNotMatchText {
            get {
                return ResourceManager.GetString("AmendmentsDoNotMatchText", resourceCulture);
            }
        }
        
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        public static string MobileNumberVerificationSuccessful {
            get {
                return ResourceManager.GetString("MobileNumberVerificationSuccessful", resourceCulture);
            }
        }
        
        public static string PassWordChangedSucessfully {
            get {
                return ResourceManager.GetString("PassWordChangedSucessfully", resourceCulture);
            }
        }
        
        public static string Pdf {
            get {
                return ResourceManager.GetString("Pdf", resourceCulture);
            }
        }
        
        public static string PdfIsNoteAvailable {
            get {
                return ResourceManager.GetString("PdfIsNoteAvailable", resourceCulture);
            }
        }
        
        public static string TinEmail {
            get {
                return ResourceManager.GetString("TinEmail", resourceCulture);
            }
        }
        
        public static string MobileNumberUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MobileNumberUpdatedSuccessfully", resourceCulture);
            }
        }
        
        public static string DetailsChangedSuccessfully {
            get {
                return ResourceManager.GetString("DetailsChangedSuccessfully", resourceCulture);
            }
        }
        
        public static string Emailverificationcodesentsuccessfully {
            get {
                return ResourceManager.GetString("Emailverificationcodesentsuccessfully", resourceCulture);
            }
        }
        
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        public static string LogoutConfirmationMessage {
            get {
                return ResourceManager.GetString("LogoutConfirmationMessage", resourceCulture);
            }
        }
        
        public static string NewEmailandRetypeEmailNotMatch {
            get {
                return ResourceManager.GetString("NewEmailandRetypeEmailNotMatch", resourceCulture);
            }
        }
        
        public static string NewPasswordandRetypePasswordNotMatch {
            get {
                return ResourceManager.GetString("NewPasswordandRetypePasswordNotMatch", resourceCulture);
            }
        }
        
        public static string EnterVerificationCodeForEmail {
            get {
                return ResourceManager.GetString("EnterVerificationCodeForEmail", resourceCulture);
            }
        }
        
        public static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        public static string EnterNewMobileNumber {
            get {
                return ResourceManager.GetString("EnterNewMobileNumber", resourceCulture);
            }
        }
        
        public static string EnterValidMobileNumber {
            get {
                return ResourceManager.GetString("EnterValidMobileNumber", resourceCulture);
            }
        }
        public static string Information
        {
            get
            {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        public static string OkText
        {
            get
            {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        public static string TaxPayerProfile
        {
            get
            {
                return ResourceManager.GetString("TaxPayerProfile", resourceCulture);
            }
        }
        public static string UserAuthenticationFailed
        {
            get
            {
                return ResourceManager.GetString("UserAuthenticationFailed", resourceCulture);
            }
        }
        public static string UserDoesNotExist
        {
            get
            {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        public static string UserAccountLocked
        {
            get
            {
                return ResourceManager.GetString("UserAccountLocked", resourceCulture);
            }
        }
        public static string PleaseReVerify
        {
            get
            {
                return ResourceManager.GetString("PleaseReVerify", resourceCulture);
            }
        }
    }
}
