<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<RootNamespace>EGAZT</RootNamespace>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>pdbonly</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="ViewModel\SyncFusionEnabledViewModel\CorrespondancePage\**" />
	  <Compile Remove="ViewModel\SyncFusionEnabledViewModel\CorrespondenceDetailsPage\**" />
	  <Compile Remove="Views\NewDesign\Template\NewFolder\**" />
	  <Compile Remove="Views\SyncFusionEnabledViews\AccountCreatedPages\**" />
	  <Compile Remove="Views\SyncFusionEnabledViews\CheckTINStatusPages\**" />
	  <Compile Remove="Views\SyncFusionEnabledViews\CorrespondancePages\**" />
	  <Compile Remove="Views\SyncFusionEnabledViews\CorrespondenceDetailsPages\**" />
	  <Compile Remove="Views\SyncFusionEnabledViews\MyBillsPages\**" />
	  <Compile Remove="Views\SyncFusionEnabledViews\MyCertificatePages\**" />
	  <Compile Remove="Views\SyncFusionEnabledViews\MyCommitmentsPage\**" />
	  <Compile Remove="Views\SyncFusionEnabledViews\MyReturnPagesNew\**" />
	  <Compile Remove="Views\SyncFusionEnabledViews\ReturnsPages\**" />
	  <Compile Remove="Views\SyncFusionEnabledViews\SigupPages\**" />
	  <Compile Remove="Views\SyncFusionEnabledViews\TaxEvasionPages\**" />
	  <Compile Remove="Views\SyncFusionEnabledViews\VATLookUpPages\**" />
	  <EmbeddedResource Remove="ViewModel\SyncFusionEnabledViewModel\CorrespondancePage\**" />
	  <EmbeddedResource Remove="ViewModel\SyncFusionEnabledViewModel\CorrespondenceDetailsPage\**" />
	  <EmbeddedResource Remove="Views\NewDesign\Template\NewFolder\**" />
	  <EmbeddedResource Remove="Views\SyncFusionEnabledViews\AccountCreatedPages\**" />
	  <EmbeddedResource Remove="Views\SyncFusionEnabledViews\CheckTINStatusPages\**" />
	  <EmbeddedResource Remove="Views\SyncFusionEnabledViews\CorrespondancePages\**" />
	  <EmbeddedResource Remove="Views\SyncFusionEnabledViews\CorrespondenceDetailsPages\**" />
	  <EmbeddedResource Remove="Views\SyncFusionEnabledViews\MyBillsPages\**" />
	  <EmbeddedResource Remove="Views\SyncFusionEnabledViews\MyCertificatePages\**" />
	  <EmbeddedResource Remove="Views\SyncFusionEnabledViews\MyCommitmentsPage\**" />
	  <EmbeddedResource Remove="Views\SyncFusionEnabledViews\MyReturnPagesNew\**" />
	  <EmbeddedResource Remove="Views\SyncFusionEnabledViews\ReturnsPages\**" />
	  <EmbeddedResource Remove="Views\SyncFusionEnabledViews\SigupPages\**" />
	  <EmbeddedResource Remove="Views\SyncFusionEnabledViews\TaxEvasionPages\**" />
	  <EmbeddedResource Remove="Views\SyncFusionEnabledViews\VATLookUpPages\**" />
	  <None Remove="ViewModel\SyncFusionEnabledViewModel\CorrespondancePage\**" />
	  <None Remove="ViewModel\SyncFusionEnabledViewModel\CorrespondenceDetailsPage\**" />
	  <None Remove="Views\NewDesign\Template\NewFolder\**" />
	  <None Remove="Views\SyncFusionEnabledViews\AccountCreatedPages\**" />
	  <None Remove="Views\SyncFusionEnabledViews\CheckTINStatusPages\**" />
	  <None Remove="Views\SyncFusionEnabledViews\CorrespondancePages\**" />
	  <None Remove="Views\SyncFusionEnabledViews\CorrespondenceDetailsPages\**" />
	  <None Remove="Views\SyncFusionEnabledViews\MyBillsPages\**" />
	  <None Remove="Views\SyncFusionEnabledViews\MyCertificatePages\**" />
	  <None Remove="Views\SyncFusionEnabledViews\MyCommitmentsPage\**" />
	  <None Remove="Views\SyncFusionEnabledViews\MyReturnPagesNew\**" />
	  <None Remove="Views\SyncFusionEnabledViews\ReturnsPages\**" />
	  <None Remove="Views\SyncFusionEnabledViews\SigupPages\**" />
	  <None Remove="Views\SyncFusionEnabledViews\TaxEvasionPages\**" />
	  <None Remove="Views\SyncFusionEnabledViews\VATLookUpPages\**" />
	  <None Remove="ViewModel\SyncFusionEnabledViewModel\Customs\" />
	  <!-- <EmbeddedResource Remove="Views\NewDesign\EstimatedZAKATReturnsPages\ReturnPortalNavigationPopUp.xaml" />
	  <EmbeddedResource Remove="Views\NewDesign\SupportPages\ZatcaInfoMenuPageView.xaml" />
	  <Compile Remove="ViewModel\NewDesignViewModel\SupportPageVM\ZatcaInfoMenuPageViewModel.cs" />
	  <Compile Remove="Models\MyBillsFilterDropdown.cs" />
	  <Compile Remove="Models\EnumModels\CustomsEnum.cs" />
	  <Compile Remove="Views\NewDesign\EstimatedZAKATReturnsPages\ReturnPortalNavigationPopUp.xaml.cs" />
	  <Compile Remove="Views\NewDesign\SupportPages\ZatcaInfoMenuPageView.xaml.cs" /> -->
	  <None Remove="ViewModel\NewDesignViewModel\ZakatExemptionRequest\" />
	  <None Remove="Xamarin.CommunityToolkit" />
	  <None Remove="Views\NewDesign\CustomServicesPages\" />
	  <None Remove="ViewModel\NewDesignViewModel\CustomServicesViewModels\" />
	  <None Remove="Models\CustomServices\" />
	  <None Remove="Converters\" />
	  <None Remove="Services\" />
	  <None Remove="Prism.Unity.Forms" />
	  <None Remove="Services\Interface\" />
	  <None Remove="Services\Classes\" />
	  <None Remove="Behaviors\" />
	  <None Remove="Models\CustomServices\TraiffSection\" />
	  <None Remove="Controls\" />
	  <None Remove="Models\CustomServices\BalaghModels\" />
	  <None Remove="Acr.UserDialogs" />
	  <None Remove="Views\NewDesign\TahqaqViews\" />
	  <None Remove="ViewModel\NewDesignViewModel\TahqaqViewModels\" />
	  <None Remove="Models\TahqaqModels\" />
	  <None Remove="Views\NewDesign\VAT\" />
	  <None Remove="ViewModel\NewDesignViewModel\VAT\" />
	  <None Remove="ZXing.Net.Mobile" />
	  <None Remove="ZXing.Net.MobileX.Forms" />
	  <None Remove="ZXing.Net.Mobile.Forms" />
	  <None Remove="Views\NewDesign\SubmitReport\" />
	  <None Remove="ViewModel\NewDesignViewModel\SubmitReport\" />
	  <None Remove="Views\NewDesign\CustomServicesPages\e-Declarations\" />
	  <None Remove="ViewModel\NewDesignViewModel\HomeViewModels\" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Rg.Plugins.Popup" Version="2.1.0" />
		<PackageReference Include="Syncfusion.Xamarin.Buttons" Version="20.1.0.61" />
		<PackageReference Include="Syncfusion.Xamarin.Cards" Version="20.1.0.61" />
		<PackageReference Include="Syncfusion.Xamarin.SfBusyIndicator" Version="20.1.0.61" />
		<PackageReference Include="Syncfusion.Xamarin.SfCalendar" Version="20.1.0.61" />
		<PackageReference Include="Syncfusion.Xamarin.SfChart" Version="20.1.0.61" />
		<PackageReference Include="Syncfusion.Xamarin.SfListView" Version="20.1.0.61" />
		<PackageReference Include="Syncfusion.Xamarin.SfPicker" Version="20.1.0.61" />
		<PackageReference Include="Syncfusion.Xamarin.SfProgressBar" Version="20.1.0.61" />
		<PackageReference Include="Syncfusion.Xamarin.SfTabView" Version="20.1.0.61" />
		<PackageReference Include="System.Linq" Version="4.3.0" />
		<PackageReference Include="System.ServiceModel.Duplex" Version="4.9.0" />
		<PackageReference Include="System.ServiceModel.Http" Version="4.9.0" />
		<PackageReference Include="System.ServiceModel.NetTcp" Version="4.9.0" />
		<PackageReference Include="System.ServiceModel.Security" Version="4.9.0" />
		<PackageReference Include="Xam.Plugin.Media" Version="5.0.1" />
		<PackageReference Include="Xamarin.Essentials" Version="1.7.3" />
		<PackageReference Include="Xamarin.Forms" Version="5.0.0.2478" />
		<PackageReference Include="CardsView" Version="2.8.1" />
		<PackageReference Include="MvvmLight" Version="5.4.1.1" />
		<PackageReference Include="MvvmLightLibs" Version="5.4.1.1" />
		<PackageReference Include="CommonServiceLocator" Version="2.0.6" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
		<PackageReference Include="Xam.Plugin.Connectivity" Version="3.2.0" />
		<PackageReference Include="Xamarin.Forms.Maps" Version="5.0.0.2478" />
		<PackageReference Include="Xamarin.Forms.PancakeView" Version="2.3.0.759" />
		<PackageReference Include="Xamarin.Plugin.FilePicker" Version="2.1.41" />
		<PackageReference Include="Syncfusion.Xamarin.Core" Version="20.1.0.61" />
		<PackageReference Include="Syncfusion.Xamarin.SfPdfViewer" Version="20.1.0.61" />
		<PackageReference Include="Xamarin.Forms.GoogleMaps" Version="3.3.0" />
		<PackageReference Include="Xamarin.Build.Download" Version="0.11.2" />
		<PackageReference Include="Xamarin.CommunityToolkit" Version="2.0.2" />
		<PackageReference Include="AppDynamics.Agent" Version="2020.11.0" />
	        <PackageReference Include="Prism.Unity.Forms" Version="8.1.97" />
	        <PackageReference Include="Acr.UserDialogs" Version="7.2.0.564" />
	        <PackageReference Include="ZXing.Net.MobileX.Forms" Version="3.0.1" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="LogInView.cs" />
		<Compile Remove="Views\BorderlessEntry.xaml.cs" />
		<Compile Remove="Helper\IHTTPClientHandlerCreationService.cs" />
		<Compile Remove="Models\AttachmentPageView.xaml.cs" />
		<Compile Remove="Views\SyncFusionEnabledViews\VATRefundsListPageView.xaml.cs" />
		<Compile Remove="ViewModel\NewDesignViewModel\Instructions\ContractReleasePageView.xaml.cs" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Connected Services\" />
		<Folder Include="Effect\" />
		<Folder Include="SyncFusionEnabledBehaviors\" />
		<Folder Include="ViewModel\SyncFusionEnabledViewModel\TaxEvasionRegistrationPage\" />
		<Folder Include="Views\SyncFusionEnabledViews\ActivityIndicator\" />
		<Folder Include="Views\SyncFusionEnabledViews\UnlockAccount\" />
		<Folder Include="ViewModel\SyncFusionEnabledViewModel\UnlockAccount\" />
		<Folder Include="Views\NewDesign\ZakatDeregistration\" />
		<Folder Include="ViewModel\SyncFusionEnabledViewModel\ZakatDeregistration\" />
		<Folder Include="Views\NewDesign\VATLookUp\" />
		<Folder Include="Views\NewDesign\VATDeRegistration\" />
		<Folder Include="Views\NewDesign\GenericPickers\" />
		<Folder Include="ViewModel\NewDesignViewModel\GenericPickers\" />
		<Folder Include="Views\NewDesign\EstablishmentRegistrationPages\" />
		<Folder Include="Views\NewDesign\ZakatInstalmentPlan\" />
		<Folder Include="ViewModel\NewDesignViewModel\ZakatInstalmentViewModel\" />
		<Folder Include="Models\ZakatInstalationModels\" />
		<Folder Include="Views\NewDesign\VATRefunds\" />
		<Folder Include="ViewModel\NewDesignViewModel\VATRefunds\" />
		<Folder Include="Models\VATRefunds\" />
		<Folder Include="ViewModel\NewDesignViewModel\TaxpayerProfileVM\" />
		<Folder Include="ViewModel\NewDesignViewModel\EstablishmentRegistration\" />
		<Folder Include="Models\EstablishmentRegistration\" />
		<Folder Include="GAZTDLL\" />
		<Folder Include="GAZTDLL\Droid\" />
		<Folder Include="GAZTDLL\iOS\" />
		<Folder Include="Views\NewDesign\VATRegistrationDetails\" />
		<Folder Include="Models\AccountStatements\" />
		<Folder Include="ViewModel\NewDesignViewModel\Common\" />
		<Folder Include="ViewModel\SyncFusionEnabledViewModel\ChecKTINStatusPage\" />
		<Folder Include="ViewModel\NewDesignViewModel\PaymnetOptions\" />
		<Folder Include="EGAZT\ViewModel\" />
		<Folder Include="ViewModel\SyncFusionEnabledViewModel\Customs\" />
		<Folder Include="Views\NewDesign\CustomServicesPages\" />
		<Folder Include="ViewModel\NewDesignViewModel\CustomServicesViewModels\" />
		<Folder Include="Models\CustomServices\" />
		<Folder Include="Converters\" />
		<Folder Include="Services\" />
		<Folder Include="Services\Interface\" />
		<Folder Include="Services\Classes\" />
		<Folder Include="Behaviors\" />
		<Folder Include="Models\CustomServices\TraiffSection\" />
		<Folder Include="Models\CustomServices\BalaghModels\" />
		<Folder Include="Views\NewDesign\TahqaqViews\" />
		<Folder Include="ViewModel\NewDesignViewModel\TahqaqViewModels\" />
		<Folder Include="Models\TahqaqModels\" />
		<Folder Include="Views\NewDesign\VAT\" />
		<Folder Include="ViewModel\NewDesignViewModel\VAT\" />
		<Folder Include="ViewModel\NewDesignViewModel\SubmitReport\" />
		<Folder Include="Views\NewDesign\CustomServicesPages\e-Declarations\" />
		<Folder Include="ViewModel\NewDesignViewModel\HomeViewModels\" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Remove="Views\BorderlessEntry.xaml" />
		<EmbeddedResource Remove="ViewModel\NewDesignViewModel\DashBoardPageViewModel\DashBoardPageView.xaml" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="AppResources.ar.Designer.cs">
			<DependentUpon>AppResources.ar.resx</DependentUpon>
		</Compile>
		<Compile Update="SyncfusionControl.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>SyncfusionControl.resx</DependentUpon>
		</Compile>
		<Compile Update="Views\NewDesign\AccountStatements\AccountStatementBillsPageView.xaml.cs">
		  <DependentUpon>AccountStatementBillsPageView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\NewDesign\TaxpayerProfile\UpdatePasswordPopUp.xaml.cs">
			<DependentUpon>UpdatePasswordPopUp.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\NewDesign\Template\DashboardAnonymousMenuPageView.xaml.cs">
			<DependentUpon>DashboardAnonymousMenuPageView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\NewDesign\VATDeclarationPages\MorePopUpPageView.xaml.cs">
			<DependentUpon>MorePopUpPageView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\NewDesign\OnboardingPages\OnBoardingAnimationPageView.xaml.cs">
			<DependentUpon>OnBoardingAnimationPageView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\FinancialDetailAttachmentPopupPageView.xaml.cs">
			<DependentUpon>FinancialDetailAttachmentPopupPageView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SyncFusionEnabledViews\UnlockAccount\UnlockAccountTINPageView.xaml.cs">
			<DependentUpon>UnlockAccountTINPageView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\NewDesign\VATDeRegistration\VATDeRegistrationDetailsPage.xaml.cs">
			<DependentUpon>VATDeregistrationDetailsPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\NewDesign\VATDeRegistration\VATDeRegistrationInstructionsPage.xaml.cs">
			<DependentUpon>VATDeregistrationInstructionsPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\NewDesign\ZakatDeregistration\ZakatRegistrationDetailsListPageView.xaml.cs">
			<DependentUpon>ZakatRegistrationDetailsListPageView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\NewDesign\VATRefunds\VATRefundsNewRequestPageView.xaml.cs">
			<DependentUpon>VATRefundsNewRequestPageView.xaml</DependentUpon>
		</Compile>
		<Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="Views\SyncFusionEnabledViews\VATRefundsListPageView.xaml.cs">
			<SubType>Code</SubType>
		</Compile>
		<Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="Views\NewDesign\VATRefunds\VATRefundsListPageView.xaml.cs">
			<DependentUpon>..\..\SyncFusionEnabledViews\VATRefundsListPageView.xaml</DependentUpon>
			<SubType>Code</SubType>
		</Compile>
		<Compile Update="Views\NewDesign\EstimatedZAKATReturnsPages\AttachmentInformationPopUp.xaml.cs">
			<DependentUpon>AttachmentInformationPopUp.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\NewDesign\TAXEvasionPages\NewTaxEvasionFormSuccessPaveView.xaml.cs">
			<DependentUpon>NewTaxEvasionFormSuccessPaveView.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\NewDesign\ZakatDeregistration\ZakatRegistrationTaxPayerDetails.xaml.cs">
			<DependentUpon>ZakatRegistrationTaxPayerDetails.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\NewDesign\ZakatDeregistration\ZakatRegistrationOutletsDetails.xaml.cs">
			<DependentUpon>ZakatRegistrationOutletsDetails.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\NewDesign\ZakatDeregistration\ZakatRegistrationFinancialDetails.xaml.cs">
			<DependentUpon>ZakatRegistrationFinancialDetails.xaml</DependentUpon>
		</Compile>
		<Compile Update="AppResources.Designer.cs">
		  <DependentUpon>AppResources.resx</DependentUpon>
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Update="AppResources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>AppResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Controls\ListBottomSheet.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="CustomControl\CheckboxCustom.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="SyncfusionControl.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>SyncfusionControl.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="TestPage.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\MyBillsView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\AccountStatements\AccountStatementsDetailPageView.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\AccountStatements\AccountStatementBillsPageView.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\Common\ListPopUpViewPage.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\Common\SingleButtonPopupView.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\Common\YesNoAlertPopupView.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\DashBoardPages\InfoPopUpPage.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\DashBoardPages\LogoutPageView.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\DashBoardPages\TaxManagementPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\EstablishmentAmendUpdatePages\ActivityItemAmendUpdatePage.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\EstablishmentAmendUpdatePages\EstablishmentAmendUpdateSuccessfulPage.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\EstablishmentAmendUpdatePages\OutletDetailsAmendUpdatePageView.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\EstablishmentSignUP\AccountCreatedSuccessfullyPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\EstablishmentSignUP\EstablishmentSignUPPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\EstablishmentSignUP\EstablishmentSignUpRegistrationSuccessfulForNoTINPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\EstablishmentSignUP\EstablishmentSignUpRegistrationSuccessfullPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\EstablishmentSignUP\EstablishmentSignUpRegistrationSuccessfullPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\EstablishmentSignUP\InstructionPopUpPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\EstimatedZAKATReturnsPages\AttachmentPopUp.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\EstimatedZAKATReturnsPages\ZakatReturnDetailsSuccessfullPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\ForgotPasswordPages\RecoverPasswordPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\ForgotPasswordPages\RecoverUsername.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\FormBundleStatusPages\FormBundleStatusPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\MyBillsPages\MyBillsMultiplePayableList.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\MyReturnsPages\MyReturnsNewPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\SubmitReport\ReportSuccessPage.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\SupportPages\SupportPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\TAXEvasionPages\TaxEvasionPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\TAXEvasionPages\TaxEvasionPageWebView.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\TAXEvasionPages\TaxEvasionReportDetailPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\TaxpayerCorrespondancePages\TaxpayerCorrespondancePageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\TaxpayerProfile\TaxpayerProfilePageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\TaxpayerProfile\UpdateEmailPopUp.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\TaxpayerProfile\UpdateMobilePopUp.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\TaxpayerProfile\UpdatePasswordPopUp.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\TaxpayerProfile\VerificationPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\TaxpayersCertificatesPages\TaxpayersCertificatesPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\Template\NewPublicMenuPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\Template\SelectedItemTemplate.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\Template\SelectedItemTemplateNoIcon.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\Template\UnSelectedItemTemplate.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\Template\UnSelectedItemTemplateNoIcon.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\TestPage.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATAmendReactivationPages\VATAmendReactivationPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATAmendReactivationPages\VATAmendReactivationSuccessfulPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\AdjustmentPopupPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\InstructionPopUp.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\MorePopUpPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\NewAccountPopPage.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\NotesDescriptionPopUpPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\NotesPopUpPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\RefundAccountPopupPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\RefundInstrunctions.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\ShowVatInformationConfirmationPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\ShowVatInformationForPrivatehealthCare.xaml">
		  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\ShowVatInformationPopUpPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\ForgotPasswordPages\ForgotPasswordPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\SummaryInstruction.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\VATCreditCarriedForwardPopUpPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\VATReturnSuccessfullPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATDeclarationPages\VATReturnUpdatedUIPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\Template\DashboardAnonymousMenuPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\VATServices\VATServicesPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\ZakatForm5\DummyPopUp.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\ZakatForm5\ZakatForm5PageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\ZAKATObjectionPages\NewZakatObjectionPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\ZAKATObjectionPages\ZakatObjectionSuccessfullPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\CommonStyle\StylesNewUI.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\ContactUsPage\ContactUsPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\StandardTemplate\StandardTemplateOfCardView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\StylesTestUi\StyleTestUIPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\VATDeclarationPagesEX\VATReturnsPageViewEX.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\ConfirmationPopUpForVatRegistration.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\FileAttachmentPopUpPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\FinancialDetailAttachmentPopupPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\IndividualRegistrationPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\NewAccountPopUpPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\RegistrationSuccessfulPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\VATIndividualSignupPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\VATIndividualSignupTnCPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\VATRegistrationMenuPopUp.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\VATRegistrationSuccessfullPageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Views\NewDesign\EstablishmentAmendUpdatePages\EstablishmentAmendUpdatePageView.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<None Remove="CustomControl\CustomLabel.config" />
		<None Remove="Font\MyMaterialIcon.ttf" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Font\MyMaterialIcon.ttf" />
		<None Remove=".DS_Store" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="Syncfusion.SfRotator.XForms">
			<HintPath>..\..\..\UX VD Design\RTL_Assembly-468883958\PCL\Syncfusion.SfRotator.XForms.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<WCFMetadata Include="Connected Services" />
	</ItemGroup>
	<ItemGroup>
		<None Include="Views\NewDesign\ZakatObjection\ObjectionsSelectionPageView.xaml" />
	</ItemGroup>
</Project>