<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.2.0.848062" />
    <PackageReference Include="SkiaSharp.Views.Forms" Version="1.68.0" />
    <PackageReference Include="SkiaSharp" Version="1.68.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="LogInView.cs" />
    <Compile Remove="Views\BorderlessEntry.xaml.cs" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Views\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="Views\BorderlessEntry.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="AppResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="AppResources.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="AppResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>