#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GAZT.Droid.Resource", IsApplication=true)]

namespace GAZT.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorDotsBorderColor = global::GAZT.Droid.Resource.Attribute.rotatorDotsBorderColor;
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorDotsPlacement = global::GAZT.Droid.Resource.Attribute.rotatorDotsPlacement;
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorEnableAutoPlay = global::GAZT.Droid.Resource.Attribute.rotatorEnableAutoPlay;
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorEnableLooping = global::GAZT.Droid.Resource.Attribute.rotatorEnableLooping;
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorEnableSwiping = global::GAZT.Droid.Resource.Attribute.rotatorEnableSwiping;
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorNavigationDelay = global::GAZT.Droid.Resource.Attribute.rotatorNavigationDelay;
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorNavigationDirection = global::GAZT.Droid.Resource.Attribute.rotatorNavigationDirection;
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorNavigationStripMode = global::GAZT.Droid.Resource.Attribute.rotatorNavigationStripMode;
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorNavigationStripPosition = global::GAZT.Droid.Resource.Attribute.rotatorNavigationStripPosition;
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorPlayDirection = global::GAZT.Droid.Resource.Attribute.rotatorPlayDirection;
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorSelectedDotsColor = global::GAZT.Droid.Resource.Attribute.rotatorSelectedDotsColor;
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorSelectedIndex = global::GAZT.Droid.Resource.Attribute.rotatorSelectedIndex;
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorTextVisible = global::GAZT.Droid.Resource.Attribute.rotatorTextVisible;
			global::Com.Syncfusion.Rotator.Resource.Attribute.rotatorUnselectedDotsColor = global::GAZT.Droid.Resource.Attribute.rotatorUnselectedDotsColor;
			global::Com.Syncfusion.Rotator.Resource.Dimension.btn_Size = global::GAZT.Droid.Resource.Dimension.btn_Size;
			global::Com.Syncfusion.Rotator.Resource.Dimension.conc_circle = global::GAZT.Droid.Resource.Dimension.conc_circle;
			global::Com.Syncfusion.Rotator.Resource.Dimension.dot_space = global::GAZT.Droid.Resource.Dimension.dot_space;
			global::Com.Syncfusion.Rotator.Resource.Dimension.inner_circle = global::GAZT.Droid.Resource.Dimension.inner_circle;
			global::Com.Syncfusion.Rotator.Resource.Dimension.outerCircle = global::GAZT.Droid.Resource.Dimension.outerCircle;
			global::Com.Syncfusion.Rotator.Resource.Dimension.thumb_padding = global::GAZT.Droid.Resource.Dimension.thumb_padding;
			global::Com.Syncfusion.Rotator.Resource.Id.Bottom = global::GAZT.Droid.Resource.Id.Bottom;
			global::Com.Syncfusion.Rotator.Resource.Id.Default = global::GAZT.Droid.Resource.Id.Default;
			global::Com.Syncfusion.Rotator.Resource.Id.Dots = global::GAZT.Droid.Resource.Id.Dots;
			global::Com.Syncfusion.Rotator.Resource.Id.Horizontal = global::GAZT.Droid.Resource.Id.Horizontal;
			global::Com.Syncfusion.Rotator.Resource.Id.Left = global::GAZT.Droid.Resource.Id.Left;
			global::Com.Syncfusion.Rotator.Resource.Id.MoveBackward = global::GAZT.Droid.Resource.Id.MoveBackward;
			global::Com.Syncfusion.Rotator.Resource.Id.MoveForward = global::GAZT.Droid.Resource.Id.MoveForward;
			global::Com.Syncfusion.Rotator.Resource.Id.None = global::GAZT.Droid.Resource.Id.None;
			global::Com.Syncfusion.Rotator.Resource.Id.OutSide = global::GAZT.Droid.Resource.Id.OutSide;
			global::Com.Syncfusion.Rotator.Resource.Id.Right = global::GAZT.Droid.Resource.Id.Right;
			global::Com.Syncfusion.Rotator.Resource.Id.Thumbnail = global::GAZT.Droid.Resource.Id.Thumbnail;
			global::Com.Syncfusion.Rotator.Resource.Id.Top = global::GAZT.Droid.Resource.Id.Top;
			global::Com.Syncfusion.Rotator.Resource.Id.Vertical = global::GAZT.Droid.Resource.Id.Vertical;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator = global::GAZT.Droid.Resource.Styleable.SfRotator;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorDotsBorderColor = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorDotsBorderColor;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorDotsPlacement = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorDotsPlacement;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorEnableAutoPlay = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorEnableAutoPlay;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorEnableLooping = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorEnableLooping;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorEnableSwiping = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorEnableSwiping;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorNavigationDelay = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorNavigationDelay;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorNavigationDirection = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorNavigationDirection;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorNavigationStripMode = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorNavigationStripMode;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorNavigationStripPosition = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorNavigationStripPosition;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorPlayDirection = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorPlayDirection;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorSelectedDotsColor = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorSelectedDotsColor;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorSelectedIndex = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorSelectedIndex;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorTextVisible = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorTextVisible;
			global::Com.Syncfusion.Rotator.Resource.Styleable.SfRotator_rotatorUnselectedDotsColor = global::GAZT.Droid.Resource.Styleable.SfRotator_rotatorUnselectedDotsColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int rotatorDotsBorderColor = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int rotatorDotsPlacement = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int rotatorEnableAutoPlay = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int rotatorEnableLooping = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int rotatorEnableSwiping = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int rotatorNavigationDelay = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int rotatorNavigationDirection = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int rotatorNavigationStripMode = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int rotatorNavigationStripPosition = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int rotatorPlayDirection = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int rotatorSelectedDotsColor = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int rotatorSelectedIndex = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int rotatorTextVisible = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int rotatorUnselectedDotsColor = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int colorAccent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colorPrimary = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int colorPrimaryDark = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int launcher_background = 2130837507;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int btn_Size = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int conc_circle = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int dot_space = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int inner_circle = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int outerCircle = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int thumb_padding = 2130903045;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int About = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Account_statment = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int Account_statment_Gray = 2130968578;
			
			// aapt resource value: 0x7F040022
			public const int add = 2130968610;
			
			// aapt resource value: 0x7F040023
			public const int amount = 2130968611;
			
			// aapt resource value: 0x7F040024
			public const int amount_white = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int arrowDropdown = 2130968613;
			
			// aapt resource value: 0x7F040026
			public const int arrowLeft = 2130968614;
			
			// aapt resource value: 0x7F040027
			public const int arrowLeftwhite = 2130968615;
			
			// aapt resource value: 0x7F040028
			public const int arrowRight = 2130968616;
			
			// aapt resource value: 0x7F040003
			public const int ArrowUp = 2130968579;
			
			// aapt resource value: 0x7F040029
			public const int bell_notification = 2130968617;
			
			// aapt resource value: 0x7F040004
			public const int Bg_Bottom_nav = 2130968580;
			
			// aapt resource value: 0x7F04002A
			public const int branchLocator = 2130968618;
			
			// aapt resource value: 0x7F040005
			public const int Burger = 2130968581;
			
			// aapt resource value: 0x7F04002B
			public const int calendar = 2130968619;
			
			// aapt resource value: 0x7F04002C
			public const int centered = 2130968620;
			
			// aapt resource value: 0x7F040006
			public const int ChartBar = 2130968582;
			
			// aapt resource value: 0x7F04002D
			public const int chat = 2130968621;
			
			// aapt resource value: 0x7F04002F
			public const int checked_box = 2130968623;
			
			// aapt resource value: 0x7F04002E
			public const int check_oval = 2130968622;
			
			// aapt resource value: 0x7F040030
			public const int circle_arrow_right = 2130968624;
			
			// aapt resource value: 0x7F040031
			public const int clock = 2130968625;
			
			// aapt resource value: 0x7F040032
			public const int clockNew = 2130968626;
			
			// aapt resource value: 0x7F040033
			public const int close = 2130968627;
			
			// aapt resource value: 0x7F040034
			public const int closeGrey = 2130968628;
			
			// aapt resource value: 0x7F040007
			public const int ColorChat = 2130968583;
			
			// aapt resource value: 0x7F040035
			public const int committments_onboarding = 2130968629;
			
			// aapt resource value: 0x7F040036
			public const int confirmnew = 2130968630;
			
			// aapt resource value: 0x7F040037
			public const int customerService = 2130968631;
			
			// aapt resource value: 0x7F040038
			public const int customerServiceColor = 2130968632;
			
			// aapt resource value: 0x7F040039
			public const int declaration = 2130968633;
			
			// aapt resource value: 0x7F04003A
			public const int deregistration = 2130968634;
			
			// aapt resource value: 0x7F04003B
			public const int details = 2130968635;
			
			// aapt resource value: 0x7F04003C
			public const int documents_Green = 2130968636;
			
			// aapt resource value: 0x7F04003D
			public const int documents_White = 2130968637;
			
			// aapt resource value: 0x7F04003E
			public const int download = 2130968638;
			
			// aapt resource value: 0x7F040008
			public const int Ellipse = 2130968584;
			
			// aapt resource value: 0x7F04003F
			public const int email = 2130968639;
			
			// aapt resource value: 0x7F040009
			public const int Entry_DropDown = 2130968585;
			
			// aapt resource value: 0x7F040040
			public const int error = 2130968640;
			
			// aapt resource value: 0x7F040041
			public const int errorNew = 2130968641;
			
			// aapt resource value: 0x7F040042
			public const int establishments = 2130968642;
			
			// aapt resource value: 0x7F040043
			public const int establishments_BigGreen = 2130968643;
			
			// aapt resource value: 0x7F040044
			public const int establishments_White = 2130968644;
			
			// aapt resource value: 0x7F040045
			public const int eyehide = 2130968645;
			
			// aapt resource value: 0x7F040046
			public const int eyeshow = 2130968646;
			
			// aapt resource value: 0x7F040047
			public const int faQs = 2130968647;
			
			// aapt resource value: 0x7F040048
			public const int file = 2130968648;
			
			// aapt resource value: 0x7F040049
			public const int filter = 2130968649;
			
			// aapt resource value: 0x7F04004A
			public const int finances = 2130968650;
			
			// aapt resource value: 0x7F04000C
			public const int Flash = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int Forget_ic_success = 2130968589;
			
			// aapt resource value: 0x7F04000A
			public const int FP_selected_tile = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int FP_unselected_tile = 2130968587;
			
			// aapt resource value: 0x7F04000E
			public const int Generic_attachment_icon = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int Green_Key = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int Grey_message = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int Grey_phone = 2130968593;
			
			// aapt resource value: 0x7F04004B
			public const int grey_search = 2130968651;
			
			// aapt resource value: 0x7F04004C
			public const int group_114 = 2130968652;
			
			// aapt resource value: 0x7F04004D
			public const int hidePassword = 2130968653;
			
			// aapt resource value: 0x7F04004E
			public const int home = 2130968654;
			
			// aapt resource value: 0x7F0400A1
			public const int icon = 2130968737;
			
			// aapt resource value: 0x7F040069
			public const int ic_add1 = 2130968681;
			
			// aapt resource value: 0x7F04006A
			public const int ic_add_plus = 2130968682;
			
			// aapt resource value: 0x7F04004F
			public const int ic_Application_Status = 2130968655;
			
			// aapt resource value: 0x7F04006B
			public const int ic_attachment = 2130968683;
			
			// aapt resource value: 0x7F04006C
			public const int ic_burger = 2130968684;
			
			// aapt resource value: 0x7F04006D
			public const int ic_certificate = 2130968685;
			
			// aapt resource value: 0x7F04006E
			public const int ic_certificateColor = 2130968686;
			
			// aapt resource value: 0x7F040071
			public const int ic_checkmark = 2130968689;
			
			// aapt resource value: 0x7F04006F
			public const int ic_check_circle = 2130968687;
			
			// aapt resource value: 0x7F040070
			public const int ic_check_circle_24px = 2130968688;
			
			// aapt resource value: 0x7F040053
			public const int ic_Check_golden = 2130968659;
			
			// aapt resource value: 0x7F040050
			public const int ic_Check_Golden_TES = 2130968656;
			
			// aapt resource value: 0x7F040051
			public const int ic_Check_Gray = 2130968657;
			
			// aapt resource value: 0x7F040052
			public const int ic_Check_Mark = 2130968658;
			
			// aapt resource value: 0x7F040072
			public const int ic_close = 2130968690;
			
			// aapt resource value: 0x7F040073
			public const int ic_close_24px = 2130968691;
			
			// aapt resource value: 0x7F040054
			public const int ic_Close_Circle = 2130968660;
			
			// aapt resource value: 0x7F040074
			public const int ic_company = 2130968692;
			
			// aapt resource value: 0x7F040075
			public const int ic_delete = 2130968693;
			
			// aapt resource value: 0x7F040055
			public const int ic_Delete_disabled = 2130968661;
			
			// aapt resource value: 0x7F040076
			public const int ic_download = 2130968694;
			
			// aapt resource value: 0x7F040077
			public const int ic_dropdownOne = 2130968695;
			
			// aapt resource value: 0x7F040056
			public const int ic_Edit = 2130968662;
			
			// aapt resource value: 0x7F040078
			public const int ic_edit_gray = 2130968696;
			
			// aapt resource value: 0x7F040057
			public const int ic_Edit_red = 2130968663;
			
			// aapt resource value: 0x7F040079
			public const int ic_envelop = 2130968697;
			
			// aapt resource value: 0x7F04007A
			public const int ic_file_download = 2130968698;
			
			// aapt resource value: 0x7F040058
			public const int ic_FillingFrequency = 2130968664;
			
			// aapt resource value: 0x7F04005A
			public const int ic_Gazt = 2130968666;
			
			// aapt resource value: 0x7F040059
			public const int ic_GAZT_Logo_Text = 2130968665;
			
			// aapt resource value: 0x7F04007D
			public const int ic_iconpay = 2130968701;
			
			// aapt resource value: 0x7F04007E
			public const int ic_iconpay_white = 2130968702;
			
			// aapt resource value: 0x7F04007B
			public const int ic_icon_applelogo = 2130968699;
			
			// aapt resource value: 0x7F04007C
			public const int ic_icon_applelogo_white = 2130968700;
			
			// aapt resource value: 0x7F04005B
			public const int ic_Installplan = 2130968667;
			
			// aapt resource value: 0x7F04007F
			public const int ic_language = 2130968703;
			
			// aapt resource value: 0x7F040080
			public const int ic_launcher = 2130968704;
			
			// aapt resource value: 0x7F040081
			public const int ic_loading = 2130968705;
			
			// aapt resource value: 0x7F040082
			public const int ic_location_Outline = 2130968706;
			
			// aapt resource value: 0x7F040083
			public const int ic_logo_Dashboard = 2130968707;
			
			// aapt resource value: 0x7F040084
			public const int ic_logo_gazt = 2130968708;
			
			// aapt resource value: 0x7F040085
			public const int ic_maincheck = 2130968709;
			
			// aapt resource value: 0x7F040087
			public const int ic_menu_cr = 2130968711;
			
			// aapt resource value: 0x7F040088
			public const int ic_menu_cr_g = 2130968712;
			
			// aapt resource value: 0x7F040089
			public const int ic_menu_cr_w = 2130968713;
			
			// aapt resource value: 0x7F040086
			public const int ic_menu_Tax_check = 2130968710;
			
			// aapt resource value: 0x7F04008A
			public const int ic_menu_vfp = 2130968714;
			
			// aapt resource value: 0x7F04008B
			public const int ic_money = 2130968715;
			
			// aapt resource value: 0x7F04005C
			public const int ic_Paid = 2130968668;
			
			// aapt resource value: 0x7F04005D
			public const int ic_Payments = 2130968669;
			
			// aapt resource value: 0x7F04008C
			public const int ic_pdf = 2130968716;
			
			// aapt resource value: 0x7F04005E
			public const int ic_PrivacyPolicy = 2130968670;
			
			// aapt resource value: 0x7F04008D
			public const int ic_refresh = 2130968717;
			
			// aapt resource value: 0x7F04005F
			public const int ic_RefundR = 2130968671;
			
			// aapt resource value: 0x7F040060
			public const int ic_RegistrationDetails = 2130968672;
			
			// aapt resource value: 0x7F040061
			public const int ic_ReportTaxEvasion = 2130968673;
			
			// aapt resource value: 0x7F04008E
			public const int ic_reviewDetails = 2130968718;
			
			// aapt resource value: 0x7F04008F
			public const int ic_sadad = 2130968719;
			
			// aapt resource value: 0x7F040090
			public const int ic_sadad_white = 2130968720;
			
			// aapt resource value: 0x7F040092
			public const int ic_save_golden = 2130968722;
			
			// aapt resource value: 0x7F040091
			public const int ic_save_Gray = 2130968721;
			
			// aapt resource value: 0x7F040093
			public const int ic_star = 2130968723;
			
			// aapt resource value: 0x7F040094
			public const int ic_star_180 = 2130968724;
			
			// aapt resource value: 0x7F040095
			public const int ic_star_border = 2130968725;
			
			// aapt resource value: 0x7F040096
			public const int ic_sync_captcha = 2130968726;
			
			// aapt resource value: 0x7F040097
			public const int ic_unpaid = 2130968727;
			
			// aapt resource value: 0x7F040098
			public const int ic_unsubmitted = 2130968728;
			
			// aapt resource value: 0x7F040099
			public const int ic_unsubmitted_box = 2130968729;
			
			// aapt resource value: 0x7F04009A
			public const int ic_vatDe = 2130968730;
			
			// aapt resource value: 0x7F0400A0
			public const int ic_vatlookup = 2130968736;
			
			// aapt resource value: 0x7F040066
			public const int ic_VATservices = 2130968678;
			
			// aapt resource value: 0x7F04009B
			public const int ic_vat_amount = 2130968731;
			
			// aapt resource value: 0x7F04009C
			public const int ic_vat_bill = 2130968732;
			
			// aapt resource value: 0x7F04009D
			public const int ic_vat_check = 2130968733;
			
			// aapt resource value: 0x7F04009E
			public const int ic_vat_info = 2130968734;
			
			// aapt resource value: 0x7F040062
			public const int ic_VAT_reg = 2130968674;
			
			// aapt resource value: 0x7F040063
			public const int ic_VAT_reg_w = 2130968675;
			
			// aapt resource value: 0x7F04009F
			public const int ic_vat_return = 2130968735;
			
			// aapt resource value: 0x7F040064
			public const int ic_VAT_service = 2130968676;
			
			// aapt resource value: 0x7F040065
			public const int ic_VAT_service_w = 2130968677;
			
			// aapt resource value: 0x7F040067
			public const int ic_Version = 2130968679;
			
			// aapt resource value: 0x7F040068
			public const int ic_White_info = 2130968680;
			
			// aapt resource value: 0x7F0400A2
			public const int inbox_onboarding = 2130968738;
			
			// aapt resource value: 0x7F0400A3
			public const int individual = 2130968739;
			
			// aapt resource value: 0x7F0400A4
			public const int individual_1 = 2130968740;
			
			// aapt resource value: 0x7F0400A5
			public const int individual_32 = 2130968741;
			
			// aapt resource value: 0x7F0400A6
			public const int individual_32White = 2130968742;
			
			// aapt resource value: 0x7F0400A7
			public const int individual_G = 2130968743;
			
			// aapt resource value: 0x7F0400A8
			public const int information = 2130968744;
			
			// aapt resource value: 0x7F0400A9
			public const int installment_plan = 2130968745;
			
			// aapt resource value: 0x7F0400AA
			public const int installment_planColor = 2130968746;
			
			// aapt resource value: 0x7F0400AB
			public const int language = 2130968747;
			
			// aapt resource value: 0x7F0400AC
			public const int location_Green = 2130968748;
			
			// aapt resource value: 0x7F0400AE
			public const int logo_gazt = 2130968750;
			
			// aapt resource value: 0x7F0400AD
			public const int log_out = 2130968749;
			
			// aapt resource value: 0x7F040012
			public const int MainGrayCopy = 2130968594;
			
			// aapt resource value: 0x7F0400AF
			public const int menu_bill = 2130968751;
			
			// aapt resource value: 0x7F0400B0
			public const int menu_calendar = 2130968752;
			
			// aapt resource value: 0x7F0400B1
			public const int menu_help = 2130968753;
			
			// aapt resource value: 0x7F0400B2
			public const int menu_individual = 2130968754;
			
			// aapt resource value: 0x7F0400B3
			public const int menu_installment_plan = 2130968755;
			
			// aapt resource value: 0x7F0400B4
			public const int menu_manage_tax = 2130968756;
			
			// aapt resource value: 0x7F0400B5
			public const int menu_objections = 2130968757;
			
			// aapt resource value: 0x7F0400B6
			public const int menu_objectionsColor = 2130968758;
			
			// aapt resource value: 0x7F0400B7
			public const int menu_refund = 2130968759;
			
			// aapt resource value: 0x7F0400B8
			public const int menu_return = 2130968760;
			
			// aapt resource value: 0x7F0400B9
			public const int menu_settings = 2130968761;
			
			// aapt resource value: 0x7F0400BA
			public const int message = 2130968762;
			
			// aapt resource value: 0x7F0400BB
			public const int ministry_justice_3_x = 2130968763;
			
			// aapt resource value: 0x7F040013
			public const int My_bills_circle = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int My_cirteficte_circle = 2130968596;
			
			// aapt resource value: 0x7F0400BC
			public const int negative = 2130968764;
			
			// aapt resource value: 0x7F0400BD
			public const int newui_ic_pdf = 2130968765;
			
			// aapt resource value: 0x7F0400BE
			public const int non_submitted = 2130968766;
			
			// aapt resource value: 0x7F0400BF
			public const int onboarding = 2130968767;
			
			// aapt resource value: 0x7F0400C0
			public const int other = 2130968768;
			
			// aapt resource value: 0x7F040015
			public const int Overdue_clock = 2130968597;
			
			// aapt resource value: 0x7F0400C1
			public const int overdue_Returns = 2130968769;
			
			// aapt resource value: 0x7F040016
			public const int Paid_check = 2130968598;
			
			// aapt resource value: 0x7F0400C2
			public const int partiallay_paid_returns = 2130968770;
			
			// aapt resource value: 0x7F0400C3
			public const int partially_clock = 2130968771;
			
			// aapt resource value: 0x7F0400C4
			public const int partials_background = 2130968772;
			
			// aapt resource value: 0x7F0400C5
			public const int password_key = 2130968773;
			
			// aapt resource value: 0x7F040017
			public const int Password_selected = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int Password_unselected = 2130968600;
			
			// aapt resource value: 0x7F0400C6
			public const int paymentmethod_onboarding = 2130968774;
			
			// aapt resource value: 0x7F0400C7
			public const int phone_Green = 2130968775;
			
			// aapt resource value: 0x7F040019
			public const int Pin = 2130968601;
			
			// aapt resource value: 0x7F0400C8
			public const int positive = 2130968776;
			
			// aapt resource value: 0x7F0400CB
			public const int quick_actions = 2130968779;
			
			// aapt resource value: 0x7F0400C9
			public const int quick_Actions_Close = 2130968777;
			
			// aapt resource value: 0x7F0400CA
			public const int quick_action_2 = 2130968778;
			
			// aapt resource value: 0x7F04001B
			public const int RealStateVAT = 2130968603;
			
			// aapt resource value: 0x7F0400D6
			public const int refund = 2130968790;
			
			// aapt resource value: 0x7F0400D7
			public const int registration = 2130968791;
			
			// aapt resource value: 0x7F0400D8
			public const int request_verification = 2130968792;
			
			// aapt resource value: 0x7F04001A
			public const int ReSchedule = 2130968602;
			
			// aapt resource value: 0x7F0400DA
			public const int returnsubmission_onboarding = 2130968794;
			
			// aapt resource value: 0x7F0400D9
			public const int return_vatRefunds = 2130968793;
			
			// aapt resource value: 0x7F0400CC
			public const int re_Property_Registration = 2130968780;
			
			// aapt resource value: 0x7F0400CD
			public const int re_Property_Registration_G = 2130968781;
			
			// aapt resource value: 0x7F0400CE
			public const int re_Property_Tile_Background_White = 2130968782;
			
			// aapt resource value: 0x7F0400CF
			public const int re_Request_Verification = 2130968783;
			
			// aapt resource value: 0x7F0400D0
			public const int re_Request_Verification_W = 2130968784;
			
			// aapt resource value: 0x7F0400D1
			public const int re_Termination_Request = 2130968785;
			
			// aapt resource value: 0x7F0400D2
			public const int re_Termination_Request_W = 2130968786;
			
			// aapt resource value: 0x7F0400D3
			public const int re_Tile_Background = 2130968787;
			
			// aapt resource value: 0x7F0400D4
			public const int re_Tile_Background_S = 2130968788;
			
			// aapt resource value: 0x7F0400D5
			public const int re_Tile_Background_White = 2130968789;
			
			// aapt resource value: 0x7F0400DB
			public const int sadad_logo_ar = 2130968795;
			
			// aapt resource value: 0x7F0400DC
			public const int search = 2130968796;
			
			// aapt resource value: 0x7F0400DD
			public const int selected171x136 = 2130968797;
			
			// aapt resource value: 0x7F0400DE
			public const int sf_BannerImage = 2130968798;
			
			// aapt resource value: 0x7F0400DF
			public const int sf_BgImage_Gradient_Landscape = 2130968799;
			
			// aapt resource value: 0x7F0400E0
			public const int sf_BgImage_Gradient_PhoneLandscape = 2130968800;
			
			// aapt resource value: 0x7F0400E1
			public const int sf_BgImage_Gradient_TabletLandscape = 2130968801;
			
			// aapt resource value: 0x7F0400E2
			public const int sf_Cancel_payment = 2130968802;
			
			// aapt resource value: 0x7F0400E3
			public const int sf_Eservices = 2130968803;
			
			// aapt resource value: 0x7F0400E5
			public const int sf_Estimated_Zakat_return = 2130968805;
			
			// aapt resource value: 0x7F0400E4
			public const int sf_Estimated_Zakat_Returns = 2130968804;
			
			// aapt resource value: 0x7F0400E6
			public const int sf_Form_Bundle_Status = 2130968806;
			
			// aapt resource value: 0x7F0400F6
			public const int sf_ic_Dashboard_Logo_White = 2130968822;
			
			// aapt resource value: 0x7F0400F7
			public const int sf_ic_Help = 2130968823;
			
			// aapt resource value: 0x7F0400F8
			public const int sf_ic_Home = 2130968824;
			
			// aapt resource value: 0x7F0400F9
			public const int sf_ic_Menu = 2130968825;
			
			// aapt resource value: 0x7F0400FA
			public const int sf_ic_Overdue_Returns_Commitments = 2130968826;
			
			// aapt resource value: 0x7F0400FB
			public const int sf_ic_Overdue_Returns_White = 2130968827;
			
			// aapt resource value: 0x7F0400FC
			public const int sf_ic_Paid = 2130968828;
			
			// aapt resource value: 0x7F0400FD
			public const int sf_ic_Partially_Paid = 2130968829;
			
			// aapt resource value: 0x7F0400FE
			public const int sf_ic_Submited_Returns = 2130968830;
			
			// aapt resource value: 0x7F0400FF
			public const int sf_ic_Submited_Returns_White = 2130968831;
			
			// aapt resource value: 0x7F040100
			public const int sf_ic_Unpaid = 2130968832;
			
			// aapt resource value: 0x7F040101
			public const int sf_ic_Unpaid_Commitments = 2130968833;
			
			// aapt resource value: 0x7F040102
			public const int sf_ic_Unsubmited_Returns_White = 2130968834;
			
			// aapt resource value: 0x7F0400E7
			public const int sf_LoginBackground = 2130968807;
			
			// aapt resource value: 0x7F0400E8
			public const int sf_LoginBackgroundLand = 2130968808;
			
			// aapt resource value: 0x7F0400E9
			public const int sf_My_Bills = 2130968809;
			
			// aapt resource value: 0x7F0400EA
			public const int sf_My_Certificate = 2130968810;
			
			// aapt resource value: 0x7F0400EB
			public const int sf_OurTeam = 2130968811;
			
			// aapt resource value: 0x7F0400EC
			public const int sf_Payment = 2130968812;
			
			// aapt resource value: 0x7F0400ED
			public const int sf_Sadad_logo = 2130968813;
			
			// aapt resource value: 0x7F0400EE
			public const int sf_Service_6 = 2130968814;
			
			// aapt resource value: 0x7F0400EF
			public const int sf_Submited_Returns = 2130968815;
			
			// aapt resource value: 0x7F0400F1
			public const int sf_Tax_Evasion = 2130968817;
			
			// aapt resource value: 0x7F0400F0
			public const int sf_TIN_Status = 2130968816;
			
			// aapt resource value: 0x7F0400F2
			public const int sf_Unsubmited_Returns = 2130968818;
			
			// aapt resource value: 0x7F0400F3
			public const int sf_VAT_Declaration = 2130968819;
			
			// aapt resource value: 0x7F0400F4
			public const int sf_VAT_Lookup = 2130968820;
			
			// aapt resource value: 0x7F0400F5
			public const int sf_VerifyRequest = 2130968821;
			
			// aapt resource value: 0x7F040103
			public const int showPassword = 2130968835;
			
			// aapt resource value: 0x7F040104
			public const int splash = 2130968836;
			
			// aapt resource value: 0x7F040105
			public const int submited = 2130968837;
			
			// aapt resource value: 0x7F040106
			public const int submited_check = 2130968838;
			
			// aapt resource value: 0x7F040107
			public const int taxEvasion = 2130968839;
			
			// aapt resource value: 0x7F040108
			public const int tax_evasion = 2130968840;
			
			// aapt resource value: 0x7F040109
			public const int tax_evasion_green = 2130968841;
			
			// aapt resource value: 0x7F04010A
			public const int timeline = 2130968842;
			
			// aapt resource value: 0x7F04001C
			public const int TimeZone = 2130968604;
			
			// aapt resource value: 0x7F04010B
			public const int unchecked_box = 2130968843;
			
			// aapt resource value: 0x7F04010C
			public const int unlockaccount_clock = 2130968844;
			
			// aapt resource value: 0x7F04010D
			public const int unselected171x136 = 2130968845;
			
			// aapt resource value: 0x7F04010E
			public const int unsubmitted = 2130968846;
			
			// aapt resource value: 0x7F04010F
			public const int user = 2130968847;
			
			// aapt resource value: 0x7F04001D
			public const int Username_selected = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int Username_unselected = 2130968606;
			
			// aapt resource value: 0x7F040110
			public const int user_profile = 2130968848;
			
			// aapt resource value: 0x7F040111
			public const int vatEstablishment_G = 2130968849;
			
			// aapt resource value: 0x7F040112
			public const int vat_ic_individaualregistration = 2130968850;
			
			// aapt resource value: 0x7F040113
			public const int vat_ic_location = 2130968851;
			
			// aapt resource value: 0x7F040114
			public const int vat_ic_phone = 2130968852;
			
			// aapt resource value: 0x7F040115
			public const int vat_ic_success = 2130968853;
			
			// aapt resource value: 0x7F040116
			public const int vat_ic_taxpayerDetail = 2130968854;
			
			// aapt resource value: 0x7F040117
			public const int vat_new_Establishment_G = 2130968855;
			
			// aapt resource value: 0x7F040118
			public const int vat_new_Establishment_W = 2130968856;
			
			// aapt resource value: 0x7F040119
			public const int vat_new_Iconawesomephonealt = 2130968857;
			
			// aapt resource value: 0x7F04011A
			public const int vat_new_Iconawesomeusercircle = 2130968858;
			
			// aapt resource value: 0x7F04011B
			public const int vat_new_Iconioniciosstats = 2130968859;
			
			// aapt resource value: 0x7F04011C
			public const int vat_new_Iconmetrolocation = 2130968860;
			
			// aapt resource value: 0x7F04011D
			public const int vat_new_individual = 2130968861;
			
			// aapt resource value: 0x7F04011E
			public const int vat_new_individual_G = 2130968862;
			
			// aapt resource value: 0x7F04011F
			public const int vat_tile_IbanCard_background = 2130968863;
			
			// aapt resource value: 0x7F040120
			public const int vat_tile_IbanCard_background_white = 2130968864;
			
			// aapt resource value: 0x7F040121
			public const int vat_tile_listofsignup = 2130968865;
			
			// aapt resource value: 0x7F040122
			public const int vat_tile_listofsignup_W = 2130968866;
			
			// aapt resource value: 0x7F040123
			public const int vat_user = 2130968867;
			
			// aapt resource value: 0x7F040124
			public const int vat_user_summary = 2130968868;
			
			// aapt resource value: 0x7F04001F
			public const int ViewMode = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int WhiteCircle_arrow_right = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int Whiteclock = 2130968609;
			
			// aapt resource value: 0x7F040125
			public const int zakat_copy = 2130968869;
			
			// aapt resource value: 0x7F040126
			public const int zakat_details = 2130968870;
			
			// aapt resource value: 0x7F040127
			public const int zakat_manageTax = 2130968871;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int Bottom = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Default = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int Dots = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int Horizontal = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int Left = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int MoveBackward = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int MoveForward = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int None = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int OutSide = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int Right = 2131034121;
			
			// aapt resource value: 0x7F05000D
			public const int sliding_tabs = 2131034125;
			
			// aapt resource value: 0x7F05000A
			public const int Thumbnail = 2131034122;
			
			// aapt resource value: 0x7F05000E
			public const int toolbar = 2131034126;
			
			// aapt resource value: 0x7F05000B
			public const int Top = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int Vertical = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int Tabbar = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int Toolbar = 2131099649;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int errorNew = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int group_114 = 2131165185;
			
			// aapt resource value: 0x7F070005
			public const int icon = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int icon_round = 2131165190;
			
			// aapt resource value: 0x7F070003
			public const int ic_check_circle_24px = 2131165187;
			
			// aapt resource value: 0x7F070002
			public const int ic_Check_Golden_TES = 2131165186;
			
			// aapt resource value: 0x7F070004
			public const int ic_launcher = 2131165188;
			
			// aapt resource value: 0x7F070007
			public const int launcher_foreground = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int ministry_justice_3_x = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int partials_background = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int password = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int request_verification = 2131165195;
			
			// aapt resource value: 0x7F07000D
			public const int sf_ic = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int sf_icon = 2131165198;
			
			// aapt resource value: 0x7F07000C
			public const int sf_Launcher_Foreground = 2131165196;
			
			// aapt resource value: 0x7F07000F
			public const int taxEvasion_green = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int tax_evasion = 2131165200;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F080000
			public const int dzithqsccm2ca = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int gaztca = 2131230721;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int app_name = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int AppCompatDialogStyle = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int MainTheme = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int MainTheme_Base = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int Theme_Splash = 2131361795;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008,0x7F010009,0x7F01000A,0x7F01000B,0x7F01000C,0x7F01000D }
			public static int[] SfRotator = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 0
			public const int SfRotator_rotatorDotsBorderColor = 0;
			
			// aapt resource value: 1
			public const int SfRotator_rotatorDotsPlacement = 1;
			
			// aapt resource value: 2
			public const int SfRotator_rotatorEnableAutoPlay = 2;
			
			// aapt resource value: 3
			public const int SfRotator_rotatorEnableLooping = 3;
			
			// aapt resource value: 4
			public const int SfRotator_rotatorEnableSwiping = 4;
			
			// aapt resource value: 5
			public const int SfRotator_rotatorNavigationDelay = 5;
			
			// aapt resource value: 6
			public const int SfRotator_rotatorNavigationDirection = 6;
			
			// aapt resource value: 7
			public const int SfRotator_rotatorNavigationStripMode = 7;
			
			// aapt resource value: 8
			public const int SfRotator_rotatorNavigationStripPosition = 8;
			
			// aapt resource value: 9
			public const int SfRotator_rotatorPlayDirection = 9;
			
			// aapt resource value: 10
			public const int SfRotator_rotatorSelectedDotsColor = 10;
			
			// aapt resource value: 11
			public const int SfRotator_rotatorSelectedIndex = 11;
			
			// aapt resource value: 12
			public const int SfRotator_rotatorTextVisible = 12;
			
			// aapt resource value: 13
			public const int SfRotator_rotatorUnselectedDotsColor = 13;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0C0000
			public const int file_paths = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int network_security_config = 2131492865;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
