#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GAZT.Droid.Resource", IsApplication=true)]

namespace GAZT.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int About = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int Ellipse = 2130837505;
			
			// aapt resource value: 0x7F020008
			public const int email = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int eyehide = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int eyeshow = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int file = 2130837515;
			
			// aapt resource value: 0x7F02002F
			public const int icon = 2130837551;
			
			// aapt resource value: 0x7F020014
			public const int ic_add1 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int ic_attachment = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int ic_certificate = 2130837526;
			
			// aapt resource value: 0x7F020019
			public const int ic_checkmark = 2130837529;
			
			// aapt resource value: 0x7F020017
			public const int ic_check_circle = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int ic_check_circle_24px = 2130837528;
			
			// aapt resource value: 0x7F02000F
			public const int ic_Check_golden = 2130837519;
			
			// aapt resource value: 0x7F02000C
			public const int ic_Check_Golden_TES = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int ic_Check_Gray = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int ic_Check_Mark = 2130837518;
			
			// aapt resource value: 0x7F02001A
			public const int ic_close = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int ic_close_24px = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int ic_delete = 2130837532;
			
			// aapt resource value: 0x7F020010
			public const int ic_Delete_disabled = 2130837520;
			
			// aapt resource value: 0x7F02001D
			public const int ic_download = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int ic_dropdownOne = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int ic_edit_gray = 2130837535;
			
			// aapt resource value: 0x7F020011
			public const int ic_Edit_red = 2130837521;
			
			// aapt resource value: 0x7F020020
			public const int ic_envelop = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int ic_file_download = 2130837537;
			
			// aapt resource value: 0x7F020012
			public const int ic_GAZT_Logo_Text = 2130837522;
			
			// aapt resource value: 0x7F020022
			public const int ic_language = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int ic_loading = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int ic_logo_Dashboard = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int ic_money = 2130837541;
			
			// aapt resource value: 0x7F020013
			public const int ic_Paid = 2130837523;
			
			// aapt resource value: 0x7F020026
			public const int ic_pdf = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int ic_refresh = 2130837543;
			
			// aapt resource value: 0x7F020029
			public const int ic_save_golden = 2130837545;
			
			// aapt resource value: 0x7F020028
			public const int ic_save_Gray = 2130837544;
			
			// aapt resource value: 0x7F02002A
			public const int ic_star = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int ic_star_border = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int ic_sync_captcha = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int ic_unsubmitted = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int ic_vatlookup = 2130837550;
			
			// aapt resource value: 0x7F020030
			public const int logo_gazt = 2130837552;
			
			// aapt resource value: 0x7F020002
			public const int My_bills_circle = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int My_cirteficte_circle = 2130837507;
			
			// aapt resource value: 0x7F020031
			public const int non_submitted = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int overdue_Returns = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int partiallay_paid_returns = 2130837555;
			
			// aapt resource value: 0x7F020004
			public const int Pin = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int ReSchedule = 2130837509;
			
			// aapt resource value: 0x7F020034
			public const int sadad_logo_ar = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int sf_BgImage_Gradient_Landscape = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int sf_BgImage_Gradient_PhoneLandscape = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int sf_BgImage_Gradient_TabletLandscape = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int sf_Eservices = 2130837560;
			
			// aapt resource value: 0x7F02003A
			public const int sf_Estimated_Zakat_return = 2130837562;
			
			// aapt resource value: 0x7F020039
			public const int sf_Estimated_Zakat_Returns = 2130837561;
			
			// aapt resource value: 0x7F02003B
			public const int sf_Form_Bundle_Status = 2130837563;
			
			// aapt resource value: 0x7F020048
			public const int sf_ic_Dashboard_Logo_White = 2130837576;
			
			// aapt resource value: 0x7F020049
			public const int sf_ic_Help = 2130837577;
			
			// aapt resource value: 0x7F02004A
			public const int sf_ic_Home = 2130837578;
			
			// aapt resource value: 0x7F02004B
			public const int sf_ic_Menu = 2130837579;
			
			// aapt resource value: 0x7F02004C
			public const int sf_ic_Overdue_Returns_Commitments = 2130837580;
			
			// aapt resource value: 0x7F02004D
			public const int sf_ic_Overdue_Returns_White = 2130837581;
			
			// aapt resource value: 0x7F02004E
			public const int sf_ic_Paid = 2130837582;
			
			// aapt resource value: 0x7F02004F
			public const int sf_ic_Partially_Paid = 2130837583;
			
			// aapt resource value: 0x7F020050
			public const int sf_ic_Submited_Returns = 2130837584;
			
			// aapt resource value: 0x7F020051
			public const int sf_ic_Submited_Returns_White = 2130837585;
			
			// aapt resource value: 0x7F020052
			public const int sf_ic_Unpaid = 2130837586;
			
			// aapt resource value: 0x7F020053
			public const int sf_ic_Unpaid_Commitments = 2130837587;
			
			// aapt resource value: 0x7F020054
			public const int sf_ic_Unsubmited_Returns_White = 2130837588;
			
			// aapt resource value: 0x7F02003C
			public const int sf_LoginBackground = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int sf_LoginBackgroundLand = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public const int sf_My_Bills = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public const int sf_My_Certificate = 2130837567;
			
			// aapt resource value: 0x7F020040
			public const int sf_OurTeam = 2130837568;
			
			// aapt resource value: 0x7F020041
			public const int sf_Sadad_logo = 2130837569;
			
			// aapt resource value: 0x7F020042
			public const int sf_Submited_Returns = 2130837570;
			
			// aapt resource value: 0x7F020044
			public const int sf_Tax_Evasion = 2130837572;
			
			// aapt resource value: 0x7F020043
			public const int sf_TIN_Status = 2130837571;
			
			// aapt resource value: 0x7F020045
			public const int sf_Unsubmited_Returns = 2130837573;
			
			// aapt resource value: 0x7F020046
			public const int sf_VAT_Declaration = 2130837574;
			
			// aapt resource value: 0x7F020047
			public const int sf_VAT_Lookup = 2130837575;
			
			// aapt resource value: 0x7F020055
			public const int splash = 2130837589;
			
			// aapt resource value: 0x7F020006
			public const int TimeZone = 2130837510;
			
			// aapt resource value: 0x7F020056
			public const int user = 2130837590;
			
			// aapt resource value: 0x7F020007
			public const int ViewMode = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050002
			public const int icon = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int icon_round = 2131034115;
			
			// aapt resource value: 0x7F050001
			public const int ic_check_circle_24px = 2131034113;
			
			// aapt resource value: 0x7F050000
			public const int ic_Check_Golden_TES = 2131034112;
			
			// aapt resource value: 0x7F050004
			public const int launcher_foreground = 2131034116;
			
			// aapt resource value: 0x7F050006
			public const int sf_ic = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int sf_icon = 2131034119;
			
			// aapt resource value: 0x7F050005
			public const int sf_Launcher_Foreground = 2131034117;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppCompatDialogStyle = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int MainTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int MainTheme_Base = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int Theme_Splash = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
