using System;
using System.Collections.Generic;

namespace ZakatForm5Model
{
    public partial class ZakatForm5DataResult
    {
        public ZakatForm5Data ZakatForm5DataSet { get; set; }
    }

    public partial class ZakatForm5Data
    {
        public Metadata Metadata { get; set; }
        public string AttenbChk { get; set; }
        public string LibChk { get; set; }
        public string SelfAmd { get; set; }
        public string AAccExam { get; set; }
        public string APayAmtTp { get; set; }
        public string Govcodfg { get; set; }
        public string Gp71112Fg { get; set; }
        public string Instfg { get; set; }
        public string Msgfg { get; set; }
        public string Msgtx { get; set; }
        public string AMobile { get; set; }
        public string AActmethod { get; set; }
        public string AAdj { get; set; }
        public long? AAgree { get; set; }
        public object AAgreeDt { get; set; }
        public string AAnnSalesrevAmt { get; set; }
        public string AAnnSalesrevOu { get; set; }
        public string AAnnSalesrevPr { get; set; }
        public string AAnnSalesrevTot { get; set; }
        public string AAnnSalesrevTotFg { get; set; }
        public string AAnnualRent { get; set; }
        public string AAnnualRentFg { get; set; }
        public long? AAppAdopTp { get; set; }
        public string AArzaqIPer { get; set; }
        public long? ABondsApp { get; set; }
        public long? ABulding { get; set; }
        public string ACalendarTp { get; set; }
        public string ACapital { get; set; }
        public string ACapitalFg { get; set; }
        public string ACapitalOu { get; set; }
        public string ACdNm { get; set; }
        public string ACheckFg { get; set; }
        public string ACity { get; set; }
        public string ACompNm { get; set; }
        public string AConrevAmt { get; set; }
        public long? AConrevAmtChk { get; set; }
        public string AConrevOu { get; set; }
        public string AConrevPr { get; set; }
        public string AConrevTot { get; set; }
        public string ADistrict { get; set; }
        public string AEmail { get; set; }
        public string AExamMngr { get; set; }
        public string AFaxNo { get; set; }
        public string AFiscalCalendar { get; set; }
        public string AFiscalPeriod { get; set; }
        public string AFromDt { get; set; }
        public string AFromDtCh { get; set; }
        public string AFromDtTp { get; set; }
        public string AGenTradeAmt { get; set; }
        public string AGentradeIPer { get; set; }
        public string AGenTradeOu { get; set; }
        public string AGenTradePr { get; set; }
        public string AGenTradeTot { get; set; }
        public string ALegalSt { get; set; }
        public string ALivelihoodsAmt { get; set; }
        public string ALivelihoodsOu { get; set; }
        public string ALivelihoodsPr { get; set; }
        public string ALivelihoodsTot { get; set; }
        public string ALivestkIPer { get; set; }
        public string ALivestkVegtbAmt { get; set; }
        public string ALivestkVegtbOu { get; set; }
        public string ALivestkVegtbPr { get; set; }
        public string ALivestkVegtbTot { get; set; }
        public string AMainact { get; set; }
        public string AMainAct { get; set; }
        public string AMainActDesc { get; set; }
        public string AMangmentAudit { get; set; }
        public string AmdRsnz { get; set; }
        public string AName { get; set; }
        public string ANetIncomeOthActvAmt { get; set; }
        public long? ANetIncomeOthActvAmtChk { get; set; }
        public string ANetIncomeOthActvOu { get; set; }
        public string ANetIncomeOthActvPr { get; set; }
        public string ANetIncomeOthActvTot { get; set; }
        public string ANetTaxableAmount { get; set; }
        public string ANetTaxableAmountOu { get; set; }
        public string ANoBranches { get; set; }
        public string ANoEmp { get; set; }
        public string ANoEmpFg { get; set; }
        public string ANoFinance { get; set; }
        public string ANonsaudiCaSh { get; set; }
        public string ANonsaudiPrSh { get; set; }
        public long? ANoOfOutlet { get; set; }
        public string AOthincAmt { get; set; }
        public string AOthincOs { get; set; }
        public string AOthincPr { get; set; }
        public string AOthincTot { get; set; }
        public string AOthincTotFg { get; set; }
        public string AOwnerNmQuat { get; set; }
        public string APdRecptAmt { get; set; }
        public string APdRecptAmtChk { get; set; }
        public string APdRecptOu { get; set; }
        public string APlShare { get; set; }
        public long? APlShareChk { get; set; }
        public string APlShareFg { get; set; }
        public string APlShareOu { get; set; }
        public string APoBox { get; set; }
        public string Approvez { get; set; }
        public string APrctr { get; set; }
        public string AReleaseOfContract { get; set; }
        public string AReleaseOfContractChk { get; set; }
        public string AReleaseOfContractOu { get; set; }
        public string AResidency { get; set; }
        public string ARestpaidAmt { get; set; }
        public string ARestpaidAmtOu { get; set; }
        public string ASaudiCaSh { get; set; }
        public string ASaudiPrSh { get; set; }
        public string ASeal { get; set; }
        public string ASign { get; set; }
        public ASitedocs? ASitedocs { get; set; }
        public long? AStep { get; set; }
        public string AStreet { get; set; }
        public string ATelephone { get; set; }
        public string AToDt { get; set; }
        public string AToDtCh { get; set; }
        public string AToDtTp { get; set; }
        public string ATotAnnualSal { get; set; }
        public string ATotAnnualSalFg { get; set; }
        public string ATotOwedpaid { get; set; }
        public string ATotOwedpaidOu { get; set; }
        public string ATotProfit { get; set; }
        public string ATotProfitOu { get; set; }
        public string Auditorz { get; set; }
        public long? Augrp { get; set; }
        public string AZakat { get; set; }
        public string AZakat51 { get; set; }
        public string AZakat51Ou { get; set; }
        public string AZakatOu { get; set; }
        public string AZakatPrevYr { get; set; }
        public string AZakatPrevYrFg { get; set; }
        public string AZakatPrevYrOu { get; set; }
        public long? AZipCd { get; set; }
        public string Bpkind { get; set; }
        public string Cal { get; set; }
        public string CaseGuid { get; set; }
        public string CreateTxAssesz { get; set; }
        public string Dmodez { get; set; }
        public string Euser { get; set; }
        public string Fbguid { get; set; }
        public string Fbguid1 { get; set; }
        public string Fbnum { get; set; }
        public string Fbnumz { get; set; }
        public string FormGuid { get; set; }
        public string Formtype { get; set; }
        public string ForUser { get; set; }
        public string Forward { get; set; }
        public string Fturn { get; set; }
        public string Gp0368Fg { get; set; }
        public long? InChannel { get; set; }
        public string Incotyp { get; set; }
        public Isamend? Isamend { get; set; }
        public string Langz { get; set; }
        public string LegacyDocNo { get; set; }
        public string Line0 { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Line3 { get; set; }
        public string Line4 { get; set; }
        public string Line5 { get; set; }
        public string Line6 { get; set; }
        public string Line7 { get; set; }
        public string Line8 { get; set; }
        public string Line9 { get; set; }
        public string Mode { get; set; }
        public string Monthz { get; set; }
        public string ObjSubmitz { get; set; }
        public string Ofbnum { get; set; }
        public string OfficerUidz { get; set; }
        public string Omode { get; set; }
        public long? PeriodKeyz { get; set; }
        public string PerslText { get; set; }
        public string PortalUsrz { get; set; }
        public string RegIdz { get; set; }
        public string Rejectz { get; set; }
        public string Retguid { get; set; }
        public string Savez { get; set; }
        public string SavNot { get; set; }
        public string SkipBillingz { get; set; }
        public string Status { get; set; }
        public string Submitz { get; set; }
        public string Taxpayerz { get; set; }
        public string UserType { get; set; }
        public string Xvoidz { get; set; }
        public AttDetSet Gp038Set { get; set; }
        public AttDetSet Gp037Set { get; set; }
        public AttDetSet Sch200Set { get; set; }
        public AttDetSet Sch800Set { get; set; }
        public AttDetSet SchGp07 { get; set; }
        public AttDetSet SchGp06 { get; set; }
        public AttDetSet SchGp05 { get; set; }
        public AttDetSet SchGp04 { get; set; }
        public AttDetSet SchGp03 { get; set; }
        public AttDetSet SchGp3S2Set { get; set; }
        public AttDetSet SchGp3S1Set { get; set; }
        public AttDetSet Gp036Set { get; set; }
        public AttDetSet AttDetSet { get; set; }
        public AttDetSet SubSchCapitalSet { get; set; }
        public AttDetSet Gp034Set { get; set; }
        public AttDetSet Gp035Set { get; set; }
        public AttDetSet Gp063Set { get; set; }
        public AttDetSet Gp032Set { get; set; }
        public AttDetSet Gp061Set { get; set; }
        public AttDetSet Gp062Set { get; set; }
        public AttDetSet Gp033Set { get; set; }
        public AttDetSet MainActivitySet { get; set; }
        public AttDetSet LongTextSet { get; set; }
        public AttDetSet SchGp12 { get; set; }
        public AttDetSet SchGp11 { get; set; }
        public AttDetSet SchGp10 { get; set; }
        public AttDetSet SchGp09 { get; set; }
        public AttDetSet SchGp08 { get; set; }
        public AttDetSet SchGp02 { get; set; }
        public AttDetSet SchGp01 { get; set; }
        public AttDetSet GenSubSch { get; set; }
    }

    public partial class AttDetSet
    {
        public List<Result> Results { get; set; }
    }

    public partial class Result
    {
        public Metadata Metadata { get; set; }
        public string MarkDel { get; set; }
        public string Delflag { get; set; }
        public string Mandt { get; set; }
        public string FormGuid { get; set; }
        public string DataVersion { get; set; }
        public long? LineNo { get; set; }
        public long? RankingOrder { get; set; }
        public string ActCd { get; set; }
        public string ActDesc { get; set; }
        public string GrpNm { get; set; }
        public long? LineCnt { get; set; }
        public ASitedocs? Description { get; set; }
        public string Amount { get; set; }
        public Waers? Waers { get; set; }
        public string Flag { get; set; }
        public ASitedocs? SubDesc { get; set; }
        public string Value { get; set; }
        public string ProfitRatio { get; set; }
        public string Profit { get; set; }
        public ASitedocs? SubDescription { get; set; }
        public string ValueFg { get; set; }
        public string ProfitFg { get; set; }
        public string RecordNo { get; set; }
        public string ContractValFg { get; set; }
        public string GovCode { get; set; }
        public string StipendContrFg { get; set; }
        public string PrfOfConrtactFg { get; set; }
        public string ContractVal { get; set; }
        public string StipendContr { get; set; }
        public string PrfOfConrtact { get; set; }
        public long? TincrnoInd { get; set; }
        public string Tin { get; set; }
        public string ContractingName { get; set; }
        public long? MocContractor { get; set; }
        public string ContractDtTp { get; set; }
        public string OriginalValFg { get; set; }
        public string ContractDur { get; set; }
        public string AdjustContFg { get; set; }
        public string PreyrWrkFg { get; set; }
        public string CurryrWrkFg { get; set; }
        public string RemnWrkFg { get; set; }
        public string ContractPartyInd { get; set; }
        public string ContractSubInd { get; set; }
        public string ContractDtInd { get; set; }
        public string ContractParty { get; set; }
        public string ContractDurInd { get; set; }
        public string ContractSub { get; set; }
        public string OriginalValInd { get; set; }
        public object ContractDt { get; set; }
        public string OriginalVal { get; set; }
        public string AdjustCont { get; set; }
        public string PreyrWrk { get; set; }
        public string CurryrWrk { get; set; }
        public string RemnWrk { get; set; }
        public string Name { get; set; }
        public string ContractNo { get; set; }
        public string Fbnum { get; set; }
        public string ZakatPaid { get; set; }
        public string AgvDlyIncomeFg { get; set; }
        public Isamend? YearFg { get; set; }
        public OutletTp? OutletTp { get; set; }
        public string OutputValFg { get; set; }
        public string Crnumber { get; set; }
        public string NoOfCars { get; set; }
        public string RevenueFg { get; set; }
        public string ExpensesFg { get; set; }
        public MainInd? MainInd { get; set; }
        public string NetPftFg { get; set; }
        public string SubInd { get; set; }
        public string ContainerFg { get; set; }
        public string NoOfCarsFg { get; set; }
        public string OccRateFg { get; set; }
        public string NetPftPerFg { get; set; }
        public string AgvDlyIncome { get; set; }
        public string OccRate { get; set; }
        public string NetPftPer { get; set; }
        public string OutputVal { get; set; }
        public string Revenue { get; set; }
        public string Expenses { get; set; }
        public string NetPft { get; set; }
        public string Container { get; set; }
        public long? GenTradeICnt { get; set; }
        public string GenTradeIFg { get; set; }
        public string LivelihoodsIFg { get; set; }
        public string GenTradeI { get; set; }
        public string LiveStkAnimalsIFg { get; set; }
        public long? ArzaqICnt { get; set; }
        public string LivelihoodsI { get; set; }
        public string SuppConFg { get; set; }
        public long? LiveStkICnt { get; set; }
        public string LiveStkAnimalsI { get; set; }
        public string SalesFg { get; set; }
        public string CapitalFg { get; set; }
        public string GenTradeFg { get; set; }
        public string LivelihoodsFg { get; set; }
        public string LiveStkAnimalsFg { get; set; }
        public string ExtnProcFg { get; set; }
        public string IntnProcFg { get; set; }
        public string SuppCon { get; set; }
        public string TotalFg { get; set; }
        public string ProfitRatioFg { get; set; }
        public string Sales { get; set; }
        public string SalePrfRatio { get; set; }
        public string SalePrfRatioFg { get; set; }
        public string Capital { get; set; }
        public long? GenTradeCnt { get; set; }
        public string GenTrade { get; set; }
        public long? ArzaqCnt { get; set; }
        public string Livelihoods { get; set; }
        public long? LiveStkCnt { get; set; }
        public string LiveStkAnimals { get; set; }
        public string ExtnProc { get; set; }
        public long? IntnProcCnt { get; set; }
        public string IntnProc { get; set; }
        public string Total { get; set; }
        public string NoOfLabourFg { get; set; }
        public string NetProfit { get; set; }
        public string NoOfLabour { get; set; }
        public string FundingTotFg { get; set; }
        public string CapitalStrFg { get; set; }
        public string NetCapitalFg { get; set; }
        public string StatutoryPftFg { get; set; }
        public string FundingTot { get; set; }
        public string CapitalStr { get; set; }
        public string NetCapital { get; set; }
        public string StatutoryPft { get; set; }
        public string GovtContractProfFg { get; set; }
        public string CivilContrRevFg { get; set; }
        public string OtherIncomeFg { get; set; }
        public string TotalProfitFg { get; set; }
        public long? GovtContCnt { get; set; }
        public string GovtContractProf { get; set; }
        public long? CivilContCnt { get; set; }
        public string CivilContrRev { get; set; }
        public long? OthIncCnt { get; set; }
        public string OtherIncome { get; set; }
        public string TotalProfit { get; set; }
        public string NoOfLabours { get; set; }
        public string MinimumFg { get; set; }
        public string ObjFg { get; set; }
        public string City { get; set; }
        public string RoomRateFg { get; set; }
        public string AddRoomRateFg { get; set; }
        public string NetProfitFg { get; set; }
        public string NoOfRooms { get; set; }
        public string NoOfRoomsFg { get; set; }
        public string RoomRate { get; set; }
        public string ServicFeeFg { get; set; }
        public string AddRoomRate { get; set; }
        public string ServicFee { get; set; }
        public string Owned { get; set; }
        public string SubsidyValFg { get; set; }
        public string SubsidyVal { get; set; }
        public string IncrInCapFg { get; set; }
        public string CapitalRateFg { get; set; }
        public string ProfitsFg { get; set; }
        public string IncrInCap { get; set; }
        public string CapitalRate { get; set; }
        public string Profits { get; set; }
        public string IntrPurchaseFg { get; set; }
        public string ShareCapFg { get; set; }
        public string ForgPurchaseFg { get; set; }
        public string PerSalesGainFg { get; set; }
        public string ShareCap { get; set; }
        public string IntrPurchase { get; set; }
        public string ForgPurchase { get; set; }
        public string PerSalesGain { get; set; }
        public long? Persl { get; set; }
        public string PerslDesc { get; set; }
        public string ImportTot { get; set; }
        public string Import3RdParty { get; set; }
        public string HigherImport { get; set; }
        public string TotImpIntn { get; set; }
        public string CapitalGain { get; set; }
        public string CapitalMci { get; set; }
        public string CapitalAcc { get; set; }
        public string MaxCapital { get; set; }
        public string LoanDtTp { get; set; }
        public object LoanDt { get; set; }
        public string ApprovalDtTp { get; set; }
        public object ApprovalDt { get; set; }
        public string LoanVal { get; set; }
        public ASitedocs? NumberOfYr { get; set; }
        public string IncrCapital { get; set; }
    }

    public partial class Metadata
    {
        public Uri Id { get; set; }
        public Uri Uri { get; set; }
        public string Type { get; set; }
    }

    public enum ASitedocs { Empty, The000 };

    public enum MainInd { DeptOfZakatIncomeTax };

    public enum OutletTp { Main };

    public enum Waers { Sar };

    public enum Isamend { N, Y };
}
