<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>;net7.0-ios;net7.0-android33.0</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>ZATCAMAUI</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Display name -->
		<ApplicationTitle>ZATCAMAUI</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.zatcamaui</ApplicationId>
		<ApplicationIdGuid>c26ce74b-6e11-469c-a8c0-b07fe33a9b2d</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>
	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Remove="Platforms\Android\DependencyServices\CustomPdfRenderer.cs" />
	  <Compile Remove="Platforms\Android\DependencyServices\ForceUpdate.cs" />
	  <Compile Remove="Platforms\Android\SplashScreen.cs" />
	  <Compile Remove="Platforms\iOS\DependencyServices\ForceUpdate.cs" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="Resources\Fonts\MyMaterialIcon.ttf" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="Acr.UserDialogs" Version="8.0.1" />
		<PackageReference Include="CardsView.Maui" Version="0.0.4" />
		<PackageReference Include="CommonServiceLocator" Version="2.0.7" />
		<PackageReference Include="CommunityToolkit.Maui" Version="6.1.0" />
		<PackageReference Include="MvvmLight" Version="5.4.1.1" />
		<PackageReference Include="MvvmLightLibs" Version="5.4.1.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="PancakeViewCompat" Version="7.0.0" />
		<PackageReference Include="Plugin.MediaManager.Forms" Version="1.2.2" />
		<PackageReference Include="Portable.JWT" Version="1.0.3" />
		<PackageReference Include="Prism.Core" Version="8.1.97" />
		<PackageReference Include="RGPopup.Maui" Version="1.0.2" />
		<PackageReference Include="Syncfusion.Licensing" Version="23.2.7" />
		<PackageReference Include="Syncfusion.Maui.Buttons" Version="23.2.7" />
		<PackageReference Include="Syncfusion.Maui.Calendar" Version="23.2.7" />
		<PackageReference Include="Syncfusion.Maui.Charts" Version="23.2.7" />
		<PackageReference Include="Syncfusion.Maui.Core" Version="23.2.7" />
		<PackageReference Include="Syncfusion.Maui.Expander" Version="23.2.7" />
		<PackageReference Include="Syncfusion.Maui.Inputs" Version="23.2.7" />
		<PackageReference Include="Syncfusion.Maui.ListView" Version="23.2.7" />
		<PackageReference Include="Syncfusion.Maui.PdfViewer" Version="23.2.7" />
		<PackageReference Include="Syncfusion.Maui.Picker" Version="23.2.7" />
		<PackageReference Include="Syncfusion.Maui.ProgressBar" Version="23.2.7" />
		<PackageReference Include="Syncfusion.Maui.Scheduler" Version="23.2.7" />
		<PackageReference Include="Syncfusion.Maui.TabView" Version="23.2.7" />
		<PackageReference Include="ZXing.Net.Maui.Controls" Version="0.4.0" />
		<PackageReference Include="AppDynamics.Agent" Version="2023.2.0" />
		<PackageReference Include="AppDynamics.Agent.Maui" Version="2023.2.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="ViewModel\NewDesignViewModel\ChangeFillingPeriodViewModel\" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Condition=" '$(EnableDefaultEmbeddedResourceItems)' == 'true' " Update="AppResources.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Condition=" '$(EnableDefaultEmbeddedResourceItems)' == 'true' " Update="AppResources.ar.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>AppResources.ar.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Condition=" '$(EnableDefaultEmbeddedResourceItems)' == 'true' " Update="Syncfusion.SfPicker.XForms.ar-AE.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Syncfusion.SfPicker.XForms.ar-AE.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="AppResources.Designer.cs">
	    <DependentUpon>AppResources.resx</DependentUpon>
	  </Compile>
	  <Compile Update="AppResources.ar.Designer.cs">
	    <DependentUpon>AppResources.ar.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Syncfusion.SfPicker.XForms.ar-AE.Designer.cs">
	    <DependentUpon>Syncfusion.SfPicker.XForms.ar-AE.resx</DependentUpon>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <MauiXaml Update="Views\NewDesign\ChangeFillingPeriodPages\ChangeFillingPeriodSuccessPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\Common\FilesUploadPopUpPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\Common\InstructionsBottomPopUpView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\Common\ListPopUpViewPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\Common\MoreMenuPopUpPageViewRTwo.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\Common\SingleButtonPopupView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\DashBoardPages\LogoutPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\EstablishmentRegistrationPages\VoidNotePopPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\EstimatedZAKATReturnsPages\ReturnPortalNavigationPopUp.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\EstimatedZAKATReturnsPages\ZAKATOkCancelPopUpView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\ForgotPasswordPages\ForgotPasswordPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\ForgotPasswordPages\GAZTNewDesignRecoverPasswordPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\ForgotPasswordPages\GAZTNewDesignRecoverUsername.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\MyBillsPages\MyBillsMultiplePayableList.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\TaxpayerCorrespondancePages\TaxpayerCorrespondanceDetailPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\VATDeclarationPages\FileAttachmentPopupPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\VATDeclarationPages\MorePopUpPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\VATDeclarationPages\NewAccountPopPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\VATDeclarationPages\RefundAccountPopupPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\VATDeclarationPages\ShowVatInformationConfirmationPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\VATDeclarationPages\ShowVatInformationPopUpPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\VATDeclarationPages\VATCreditCarriedForwardPopUpPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\VATDeclarationPages\VATDeclarationAttachmentPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewDesign\VATDeRegistration\VATDeregistrationInstructionsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SyncFusionEnabledViews\AddPopPages\AddPopPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SyncFusionEnabledViews\UnlockAccount\UnlockAccountTINPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\ConfirmationPopUpForVatRegistration.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\FileAttachmentPopUpPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SyncFusionEnabledViews\VATIndividualSignupPage\NewAccountPopUpPageView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>
</Project>
